-- Generated by CSharp.lua Compiler
local System = System
local SlipeClientDx
local SlipeMtaDefinitions
local SlipeSharedUtilities
System.import(function (out)
  SlipeClientDx = Slipe.Client.Dx
  SlipeMtaDefinitions = Slipe.MtaDefinitions
  SlipeSharedUtilities = Slipe.Shared.Utilities
end)
System.namespace("Slipe.Client.Dx", function (namespace)
  -- <summary>
  -- Represents a drawable circle
  -- </summary>
  namespace.class("Circle", function (namespace)
    local Draw, __ctor1__, __ctor2__, __ctor3__
    -- <summary>
    -- Create a circle
    -- </summary>
    __ctor1__ = function (this, position, radius, color, centerColor, startAngle, stopAngle, segments, ratio, postGUI)
      SlipeClientDx.Dx2DObject.__ctor__(this)
      this:setPosition(position:__clone__())
      this.Radius = radius
      this.Color = color
      this.CenterColor = centerColor
      this.StartAngle = startAngle
      this.StopAngle = stopAngle
      this.Segments = segments
      this.Ratio = ratio
      this.PostGUI = postGUI
    end
    -- <summary>
    -- Creates a circle where the centercolor is the same as the outer color
    -- </summary>
    __ctor2__ = function (this, position, radius, color)
      __ctor1__(this, position:__clone__(), radius, color, color, 0, 360, 32, 1, false)
    end
    -- <summary>
    -- Creates a white circle
    -- </summary>
    __ctor3__ = function (this, position, radius)
      __ctor2__(this, position:__clone__(), radius, SlipeSharedUtilities.Color.getWhite())
    end
    -- <summary>
    -- Draw this circle
    -- </summary>
    Draw = function (this)
      return SlipeMtaDefinitions.MtaClient.DxDrawCircle(this:getPosition().X, this:getPosition().Y, this.Radius, this.StartAngle, this.StopAngle, this.Color:getHex(), this.CenterColor:getHex(), this.Segments, this.Ratio, this.PostGUI)
    end
    return {
      __inherits__ = function (out)
        return {
          out.Slipe.Client.Dx.Dx2DObject,
          out.Slipe.Client.Dx.IDrawable
        }
      end,
      Radius = 0,
      StartAngle = 0,
      StopAngle = 0,
      Segments = 0,
      Ratio = 0,
      Draw = Draw,
      __ctor__ = {
        __ctor1__,
        __ctor2__,
        __ctor3__
      }
    }
  end)
end)
