-- Generated by CSharp.lua Compiler
local System = System
local SlipeClientGame
local SlipeClientHelpers
local SystemNumerics
System.import(function (out)
  SlipeClientGame = Slipe.Client.Game
  SlipeClientHelpers = Slipe.Client.Helpers
  SystemNumerics = System.Numerics
end)
System.namespace("Slipe.Client.Dx", function (namespace)
  -- <summary>
  -- Class representing drawable objects
  -- </summary>
  namespace.class("Dx2DObject", function (namespace)
    local getPosition, setPosition, Update, __ctor__
    __ctor__ = function (this)
      this.pos = System.default(SystemNumerics.Vector2)
      SlipeClientHelpers.LazyAttachableObject.__ctor__(this)
    end
    getPosition = function (this)
      this:Update(0)
      return this.pos:__clone__()
    end
    setPosition = function (this, value)
      this.pos = value:__clone__()
    end
    -- <summary>
    -- Updates this DxObject to the correct position on screen
    -- </summary>
    Update = function (this, timeSlice)
      if this:getIsAttached() then
        this.pos = SlipeClientGame.GameClient.getRenderer():ScreenFromWorldPosition(SystemNumerics.Vector3.op_Addition(this:getToAttached():getPosition(), this.Offset:getTranslation()), 0, true)
      end
    end
    return {
      __inherits__ = function (out)
        return {
          out.Slipe.Client.Helpers.LazyAttachableObject
        }
      end,
      getPosition = getPosition,
      setPosition = setPosition,
      PostGUI = false,
      Update = Update,
      __ctor__ = __ctor__
    }
  end)
end)
