-- Generated by CSharp.lua Compiler
local System = System
local SlipeClientHelpers
local SlipeMtaDefinitions
local SlipeSharedUtilities
local SystemNumerics
System.import(function (out)
  SlipeClientHelpers = Slipe.Client.Helpers
  SlipeMtaDefinitions = Slipe.MtaDefinitions
  SlipeSharedUtilities = Slipe.Shared.Utilities
  SystemNumerics = System.Numerics
end)
System.namespace("Slipe.Client.Dx", function (namespace)
  namespace.class("Dx3DLine", function (namespace)
    local getStartPosition, setStartPosition, getEndPosition, setEndPosition, Draw, Update, internal, __ctor1__, 
    __ctor2__, __ctor3__
    internal = function (this)
      this.relativeEndPosition = System.default(SystemNumerics.Vector3)
      this.startPos = System.default(SystemNumerics.Vector3)
      this.endPos = System.default(SystemNumerics.Vector3)
    end
    -- <summary>
    -- Create a new 3D line
    -- </summary>
    __ctor1__ = function (this, startPos, endPos, color, width, postGUI)
      internal(this)
      SlipeClientHelpers.LazyAttachableObject.__ctor__(this)
      setStartPosition(this, startPos:__clone__())
      setEndPosition(this, endPos:__clone__())
      this.relativeEndPosition = SystemNumerics.Vector3.op_Subtraction(endPos, startPos)
      this.Color = color
      this.Width = width
      this.PostGUI = postGUI
    end
    -- <summary>
    -- Create a red line
    -- </summary>
    __ctor2__ = function (this, startPos, endPos)
      __ctor1__(this, startPos:__clone__(), endPos:__clone__(), SlipeSharedUtilities.Color.getRed(), 1, false)
    end
    -- <summary>
    -- Create a 3D line attached to a certain object
    -- </summary>
    __ctor3__ = function (this, attachedTo, relativeEndPos, offset)
      __ctor2__(this, SystemNumerics.Vector3.getZero(), relativeEndPos:__clone__())
      this:AttachTo(attachedTo, offset:__clone__())
    end
    getStartPosition = function (this)
      this:Update(0)
      return this.startPos:__clone__()
    end
    setStartPosition = function (this, value)
      this.startPos = value:__clone__()
    end
    getEndPosition = function (this)
      this:Update(0)
      return this.endPos:__clone__()
    end
    setEndPosition = function (this, value)
      this.endPos = value:__clone__()
    end
    -- <summary>
    -- Draw this line
    -- </summary>
    Draw = function (this)
      if this.Visible then
        return SlipeMtaDefinitions.MtaClient.DxDrawLine3D(getStartPosition(this).X, getStartPosition(this).Y, getStartPosition(this).Z, getEndPosition(this).X, getEndPosition(this).Y, getEndPosition(this).Z, this.Color:getHex(), this.Width, this.PostGUI)
      end
      return false
    end
    Update = function (this, timeSlice)
      if this:getIsAttached() then
        this.startPos = SystemNumerics.Vector3.op_Addition(this:getToAttached():getPosition(), this.Offset:getTranslation())
        this.endPos = SystemNumerics.Vector3.Transform(this.relativeEndPosition, SystemNumerics.Matrix4x4.op_Multiply(this:getToAttached():getMatrix(), this.Offset))
      end
    end
    return {
      __inherits__ = function (out)
        return {
          out.Slipe.Client.Helpers.LazyAttachableObject,
          out.Slipe.Client.Dx.IDrawable
        }
      end,
      getStartPosition = getStartPosition,
      setStartPosition = setStartPosition,
      getEndPosition = getEndPosition,
      setEndPosition = setEndPosition,
      Width = 0,
      PostGUI = false,
      Visible = false,
      Draw = Draw,
      Update = Update,
      __ctor__ = {
        __ctor1__,
        __ctor2__,
        __ctor3__
      }
    }
  end)
end)
