-- Generated by CSharp.lua Compiler
local System = System
local SlipeClientDx
local SlipeMtaDefinitions
local SystemNumerics
System.import(function (out)
  SlipeClientDx = Slipe.Client.Dx
  SlipeMtaDefinitions = Slipe.MtaDefinitions
  SystemNumerics = System.Numerics
end)
System.namespace("Slipe.Client.Dx", function (namespace)
  -- <summary>
  -- return MTAClient.DxDrawLine((int)start.X, (int)start.Y, (int)end.X, (int)end.Y, color.Hex, width, postGui);
  -- </summary>
  namespace.class("Line", function (namespace)
    local Draw, __ctor__
    -- <summary>
    -- Create a line instance
    -- </summary>
    __ctor__ = function (this, start, end_, color, width, postGUI)
      this.End = System.default(SystemNumerics.Vector2)
      SlipeClientDx.Dx2DObject.__ctor__(this)
      this:setPosition(start:__clone__())
      this.End = end_:__clone__()
      this.Color = color
      this.Width = width
      this.PostGUI = postGUI
    end
    -- <summary>
    -- Draw the line
    -- </summary>
    Draw = function (this)
      return SlipeMtaDefinitions.MtaClient.DxDrawLine(System.ToInt32(this:getPosition().X), System.ToInt32(this:getPosition().Y), System.ToInt32(this.End.X), System.ToInt32(this.End.Y), this.Color:getHex(), this.Width, this.PostGUI)
    end
    return {
      __inherits__ = function (out)
        return {
          out.Slipe.Client.Dx.Dx2DObject,
          out.Slipe.Client.Dx.IDrawable
        }
      end,
      Width = 0,
      Draw = Draw,
      __ctor__ = __ctor__
    }
  end)
end)
