-- Generated by CSharp.lua Compiler
local System = System
System.namespace("Slipe.Shared.Exceptions", function (namespace)
  -- <summary>
  -- Exception raised when a wrapped MTA function cannot find a requested element
  -- </summary>
  namespace.class("NullElementException", function (namespace)
    local __ctor__
    __ctor__ = function (this, message)
      System.Exception.__ctor__(this, message)
    end
    return {
      __inherits__ = function (out)
        return {
          System.Exception
        }
      end,
      __ctor__ = __ctor__
    }
  end)
end)
