-- Generated by CSharp.lua Compiler
local System = System
local SlipeMtaDefinitions
local SlipeSharedPeds
System.import(function (out)
  SlipeMtaDefinitions = Slipe.MtaDefinitions
  SlipeSharedPeds = Slipe.Shared.Peds
end)
System.namespace("Slipe.Server.Peds", function (namespace)
  -- <summary>
  -- Represents a pedestrian
  -- </summary>
  namespace.class("Ped", function (namespace)
    local getArmor1, setArmor1, getFightingStyle1, setFightingStyle1, getGravity, setGravity, getChocking1, setChocking1, 
    getHasJetpack1, setHasJetpack1, ReloadWeapon, GiveWeapon, SetAmmo, TakeAllWeapons, TakeWeapon, TakeAmmo, 
    __ctor1__, __ctor2__
    __ctor1__ = function (this, element)
      SlipeSharedPeds.SharedPed.__ctor__(this, element)
    end
    -- <summary>
    -- Create a new ped
    -- </summary>
    __ctor2__ = function (this, model, position, rotation, synced)
      __ctor1__(this, SlipeMtaDefinitions.MtaServer.CreatePed(model, position.X, position.Y, position.Z, rotation, synced))
    end
    getArmor1 = function (this)
      return SlipeMtaDefinitions.MtaShared.GetPedArmor(this.element)
    end
    setArmor1 = function (this, value)
      SlipeMtaDefinitions.MtaServer.SetPedArmor(this.element, value)
    end
    getFightingStyle1 = function (this)
      return SlipeMtaDefinitions.MtaShared.GetPedFightingStyle(this.element)
    end
    setFightingStyle1 = function (this, value)
      SlipeMtaDefinitions.MtaServer.SetPedFightingStyle(this.element, value)
    end
    getGravity = function (this)
      return SlipeMtaDefinitions.MtaServer.GetPedGravity(this.element)
    end
    setGravity = function (this, value)
      SlipeMtaDefinitions.MtaServer.SetPedGravity(this.element, value)
    end
    getChocking1 = function (this)
      return SlipeMtaDefinitions.MtaShared.IsPedChoking(this.element)
    end
    setChocking1 = function (this, value)
      SlipeMtaDefinitions.MtaServer.SetPedChoking(this.element, value)
    end
    getHasJetpack1 = function (this)
      return SlipeMtaDefinitions.MtaShared.IsPedWearingJetpack(this.element)
    end
    setHasJetpack1 = function (this, value)
      SlipeMtaDefinitions.MtaServer.SetPedWearingJetpack(this.element, value)
    end
    -- <summary>
    -- This function reloads the weapon of this ped
    -- </summary>
    ReloadWeapon = function (this)
      return SlipeMtaDefinitions.MtaServer.ReloadPedWeapon(this.element)
    end
    -- <summary>
    -- Give a weapon to this ped
    -- </summary>
    GiveWeapon = function (this, model, ammo, setAsCurrent)
      return SlipeMtaDefinitions.MtaServer.GiveWeapon(this.element, model.ID, ammo, setAsCurrent)
    end
    -- <summary>
    -- Set the total ammo of a weapon the ped has
    -- </summary>
    SetAmmo = function (this, model, totalAmmo, ammoInClip)
      return SlipeMtaDefinitions.MtaShared.SetWeaponAmmo(this.element, model.ID, totalAmmo, ammoInClip)
    end
    -- <summary>
    -- Take all weapons from this ped
    -- </summary>
    TakeAllWeapons = function (this)
      return SlipeMtaDefinitions.MtaServer.TakeAllWeapons(this.element)
    end
    -- <summary>
    -- Take a weapon from a player
    -- </summary>
    TakeWeapon = function (this, model)
      return SlipeMtaDefinitions.MtaServer.TakeWeapon(this.element, model.ID, - 1)
    end
    -- <summary>
    -- Take a certain amount of ammo from a player weapon
    -- </summary>
    TakeAmmo = function (this, model, amount)
      return SlipeMtaDefinitions.MtaServer.TakeWeapon(this.element, model.ID, amount)
    end
    return {
      __inherits__ = function (out)
        return {
          out.Slipe.Shared.Peds.SharedPed
        }
      end,
      getArmor1 = getArmor1,
      setArmor1 = setArmor1,
      getFightingStyle1 = getFightingStyle1,
      setFightingStyle1 = setFightingStyle1,
      getGravity = getGravity,
      setGravity = setGravity,
      getChocking1 = getChocking1,
      setChocking1 = setChocking1,
      getHasJetpack1 = getHasJetpack1,
      setHasJetpack1 = setHasJetpack1,
      ReloadWeapon = ReloadWeapon,
      GiveWeapon = GiveWeapon,
      SetAmmo = SetAmmo,
      TakeAllWeapons = TakeAllWeapons,
      TakeWeapon = TakeWeapon,
      TakeAmmo = TakeAmmo,
      __ctor__ = {
        __ctor1__,
        __ctor2__
      },
      __metadata__ = function (out)
        return {
          class = { 0x6, System.new(out.Slipe.Shared.Elements.DefaultElementClassAttribute, 2, 2 --[[ElementType.Ped]]) }
        }
      end
    }
  end)
end)
