-- Generated by CSharp.lua Compiler
local System = System
local SlipeClientElements
local SlipeMtaDefinitions
System.import(function (out)
  SlipeClientElements = Slipe.Client.Elements
  SlipeMtaDefinitions = Slipe.MtaDefinitions
end)
System.namespace("Slipe.Client.Assets", function (namespace)
  -- <summary>
  -- Represents a single asset file.
  -- </summary>
  namespace.class("Asset", function (namespace)
    local getFilepath, getState, HandleDownloadComplete, Download, __ctor__
    -- <summary>
    -- Creates a new asset with a specific filepath;
    -- </summary>
    __ctor__ = function (this, filepath)
      this.state = 0 --[[DownloadState.Default]]
      this.filepath = filepath

      SlipeClientElements.ResourceRootElement.OnFileDownloadComplete = SlipeClientElements.ResourceRootElement.OnFileDownloadComplete + System.fn(this, HandleDownloadComplete)
    end
    getFilepath = function (this)
      return this.filepath
    end
    getState = function (this)
      return this.state
    end
    HandleDownloadComplete = function (this, path, success)
      if path == this.filepath then
        this.state = success == true and 2 --[[DownloadState.Downloaded]] or 3 --[[DownloadState.Failed]]
        SlipeClientElements.ResourceRootElement.OnFileDownloadComplete = SlipeClientElements.ResourceRootElement.OnFileDownloadComplete - System.fn(this, HandleDownloadComplete)
        local default = this.OnDownloadComplete
        if default ~= nil then
          default()
        end
      end
    end
    -- <summary>
    -- Starts a download of the file
    -- </summary>
    Download = function (this)
      this.state = 1 --[[DownloadState.Downloading]]
      SlipeMtaDefinitions.MtaClient.DownloadFile(this.filepath)
    end
    return {
      getFilepath = getFilepath,
      state = 0,
      getState = getState,
      Download = Download,
      __ctor__ = __ctor__
    }
  end)
end)
