-- Generated by CSharp.lua Compiler
local System = System
local SlipeClientAssets
local SlipeMtaDefinitions
System.import(function (out)
  SlipeClientAssets = Slipe.Client.Assets
  SlipeMtaDefinitions = Slipe.MtaDefinitions
end)
System.namespace("Slipe.Client.Assets", function (namespace)
  -- <summary>
  -- A single DFF file
  -- </summary>
  namespace.class("Dff", function (namespace)
    local Load, ApplyTo, __ctor__
    __ctor__ = function (this, filepath)
      SlipeClientAssets.Asset.__ctor__(this, filepath)
    end
    -- <summary>
    -- Loads the DFF file into memory
    -- </summary>
    Load = function (this)
      this.dff = SlipeMtaDefinitions.MtaClient.EngineLoadDFF(this.filepath)
    end
    -- <summary>
    -- Applies the model to the game
    -- </summary>
    -- <param name="supportsAlpha"></param>
    ApplyTo = function (this, model, supportsAlpha)
      if this.dff == nil then
        System.throw(System.Exception(System.String.Format("DFF file {0} has not yet been loaded", this.filepath)))
      end

      SlipeMtaDefinitions.MtaClient.EngineReplaceModel(this.dff, model, supportsAlpha)
    end
    return {
      __inherits__ = function (out)
        return {
          out.Slipe.Client.Assets.Asset
        }
      end,
      Load = Load,
      ApplyTo = ApplyTo,
      __ctor__ = __ctor__
    }
  end)
end)
