-- Generated by CSharp.lua Compiler
local System = System
local SlipeMtaDefinitions
local SlipeSharedElements
local SlipeSharedIO
local ArrayString
System.import(function (out)
  SlipeMtaDefinitions = Slipe.MtaDefinitions
  SlipeSharedElements = Slipe.Shared.Elements
  SlipeSharedIO = Slipe.Shared.IO
  ArrayString = System.Array(System.String)
end)
System.namespace("Slipe.Client.Browsers", function (namespace)
  -- <summary>
  -- Class that wraps MTA browsers
  -- </summary>
  namespace.class("Browser", function (namespace)
    local getSettings, getCanNavigateBack, getCanNavigateForward, getTitle, getUrl, getIsLoading, getIsFocused, setVolume, 
    setRenderingPaused, setDevTools, ReloadPage, LoadUrl, Focus, GetProperty, InjectMouseDown, InjectMouseUp, 
    InjectMouseMove, InjectMouseWheel, Resize, ExecuteJavascript, ExecuteJavascript1, IsDomainBlocked, RequestDomains, RequestDomain, 
    HandleDomainRequest, HandleWhiteListChange, class, __ctor1__, __ctor2__
    __ctor1__ = function (this, element)
      SlipeSharedElements.Element.__ctor__[2](this, element)
    end
    -- <summary>
    -- Create a browser from the createBrowser parameters
    -- </summary>
    __ctor2__ = function (this, width, height, isLocal, transparent)
      __ctor1__(this, SlipeMtaDefinitions.MtaClient.CreateBrowser(width, height, isLocal, transparent))
    end
    getSettings = function ()
      return SlipeMtaDefinitions.MtaClient.GetBrowserSettings()
    end
    getCanNavigateBack = function (this)
      return SlipeMtaDefinitions.MtaClient.CanBrowserNavigateBack(this.element)
    end
    getCanNavigateForward = function (this)
      return SlipeMtaDefinitions.MtaClient.CanBrowserNavigateForward(this.element)
    end
    getTitle = function (this)
      return SlipeMtaDefinitions.MtaClient.GetBrowserTitle(this.element)
    end
    getUrl = function (this)
      return SlipeMtaDefinitions.MtaClient.GetBrowserURL(this.element)
    end
    getIsLoading = function (this)
      return SlipeMtaDefinitions.MtaClient.IsBrowserLoading(this.element)
    end
    getIsFocused = function (this)
      return SlipeMtaDefinitions.MtaClient.IsBrowserFocused(this.element)
    end
    setVolume = function (this, value)
      SlipeMtaDefinitions.MtaClient.SetBrowserVolume(this.element, value)
    end
    setRenderingPaused = function (this, value)
      SlipeMtaDefinitions.MtaClient.SetBrowserRenderingPaused(this.element, value)
    end
    setDevTools = function (this, value)
      SlipeMtaDefinitions.MtaClient.ToggleBrowserDevTools(this.element, value)
    end
    -- <summary>
    -- Reload the page of this browser
    -- </summary>
    ReloadPage = function (this)
      return SlipeMtaDefinitions.MtaClient.ReloadBrowserPage(this.element)
    end
    -- <summary>
    -- Load a specific browser URL
    -- </summary>
    LoadUrl = function (this, url, postData, urlEncoded)
      return SlipeMtaDefinitions.MtaClient.LoadBrowserURL(this.element, url, postData, urlEncoded)
    end
    -- <summary>
    -- Focus on this browser
    -- </summary>
    Focus = function (this)
      return SlipeMtaDefinitions.MtaClient.FocusBrowser(this.element)
    end
    -- <summary>
    -- Get a specific browser property
    -- </summary>
    GetProperty = function (this, key)
      return SlipeMtaDefinitions.MtaClient.GetBrowserProperty(this.element, key)
    end
    -- <summary>
    -- Inject a mousedown event in the browser
    -- </summary>
    InjectMouseDown = function (this, mouseButton)
      return SlipeMtaDefinitions.MtaClient.InjectBrowserMouseDown(this.element, mouseButton:ToEnumString(SlipeSharedIO.MouseButton):ToLower())
    end
    -- <summary>
    -- Inject a mouseup event in the browser
    -- </summary>
    InjectMouseUp = function (this, mouseButton)
      return SlipeMtaDefinitions.MtaClient.InjectBrowserMouseUp(this.element, mouseButton:ToEnumString(SlipeSharedIO.MouseButton):ToLower())
    end
    -- <summary>
    -- Inject a mousemove event to a specific position
    -- </summary>
    InjectMouseMove = function (this, position)
      return SlipeMtaDefinitions.MtaClient.InjectBrowserMouseMove(this.element, System.ToInt32(position.X), System.ToInt32(position.Y))
    end
    -- <summary>
    -- Inject a mouse scroll event
    -- </summary>
    InjectMouseWheel = function (this, vertical, horizontal)
      return SlipeMtaDefinitions.MtaClient.InjectBrowserMouseWheel(this.element, vertical, horizontal)
    end
    -- <summary>
    -- Resize the browser to specific dimensions
    -- </summary>
    Resize = function (this, dimensions)
      return SlipeMtaDefinitions.MtaClient.ResizeBrowser(this.element, dimensions.X, dimensions.Y)
    end
    -- <summary>
    -- Execute some javascript code
    -- </summary>
    ExecuteJavascript = function (this, javascript)
      System.Console.WriteLine("Executing " .. javascript)
      return SlipeMtaDefinitions.MtaClient.ExecuteBrowserJavascript(this.element, javascript)
    end
    -- <summary>
    -- Execute a javascript function using formatted js arguments
    -- </summary>
    ExecuteJavascript1 = function (this, function_, arguments)
      local javascriptString = function_ .. "("

      for _, argument in System.each(arguments) do
        javascriptString = javascriptString .. (argument:ToString() .. ", ")
      end
      javascriptString = javascriptString:Substring(0, #javascriptString - 2)

      javascriptString = javascriptString .. ")"
      return ExecuteJavascript(this, javascriptString)
    end
    -- <summary>
    -- Check if a specific domain is blocked
    -- </summary>
    IsDomainBlocked = function (domain, isURL)
      return SlipeMtaDefinitions.MtaClient.IsBrowserDomainBlocked(domain, isURL)
    end
    -- <summary>
    -- Opens a request window in order to accept the requested remote URLs
    -- </summary>
    RequestDomains = function (domains, isURL)
      return SlipeMtaDefinitions.MtaClient.RequestBrowserDomains(domains, isURL, HandleDomainRequest)
    end
    -- <summary>
    -- Opens a request window in order to accept a remote URL
    -- </summary>
    RequestDomain = function (domain, isURL)
      return RequestDomains(ArrayString(domain), isURL)
    end
    -- <summary>
    -- Handler that is triggered after a domain request was done
    -- </summary>
    HandleDomainRequest = function (wasAccepted, domains)
      for i = 0, #domains - 1 do
        local domain = domains:get(i)
        if wasAccepted then
          local default = class.OnDomainRequestAccepted
          if default ~= nil then
            default(domain)
          end
        else
          local default = class.OnDomainRequestDenied
          if default ~= nil then
            default(domain)
          end
        end
      end
    end
    HandleWhiteListChange = function (changedDomains)
      local default = class.OnWhiteListChange
      if default ~= nil then
        default(changedDomains)
      end
    end
    class = {
      __inherits__ = function (out)
        return {
          out.Slipe.Shared.Elements.Element
        }
      end,
      getSettings = getSettings,
      getCanNavigateBack = getCanNavigateBack,
      getCanNavigateForward = getCanNavigateForward,
      getTitle = getTitle,
      getUrl = getUrl,
      getIsLoading = getIsLoading,
      getIsFocused = getIsFocused,
      setVolume = setVolume,
      setRenderingPaused = setRenderingPaused,
      setDevTools = setDevTools,
      ReloadPage = ReloadPage,
      LoadUrl = LoadUrl,
      Focus = Focus,
      GetProperty = GetProperty,
      InjectMouseDown = InjectMouseDown,
      InjectMouseUp = InjectMouseUp,
      InjectMouseMove = InjectMouseMove,
      InjectMouseWheel = InjectMouseWheel,
      Resize = Resize,
      ExecuteJavascript = ExecuteJavascript,
      ExecuteJavascript1 = ExecuteJavascript1,
      IsDomainBlocked = IsDomainBlocked,
      RequestDomains = RequestDomains,
      RequestDomain = RequestDomain,
      HandleDomainRequest = HandleDomainRequest,
      HandleWhiteListChange = HandleWhiteListChange,
      __ctor__ = {
        __ctor1__,
        __ctor2__
      },
      __metadata__ = function (out)
        return {
          class = { 0x6, System.new(out.Slipe.Shared.Elements.DefaultElementClassAttribute, 2, 31 --[[ElementType.Browser]]) }
        }
      end
    }
    return class
  end)
end)
