-- Generated by CSharp.lua Compiler
local System = System
local SlipeMtaDefinitions
local SlipeServerVehicles
local SlipeSharedElements
local SlipeSharedVehicles
System.import(function (out)
  SlipeMtaDefinitions = Slipe.MtaDefinitions
  SlipeServerVehicles = Slipe.Server.Vehicles
  SlipeSharedElements = Slipe.Shared.Elements
  SlipeSharedVehicles = Slipe.Shared.Vehicles
end)
System.namespace("Slipe.Server.Vehicles", function (namespace)
  namespace.class("BaseVehicleModel", function (namespace)
    local getHandling, getVehicles, __ctor__
    __ctor__ = function (this, id)
      SlipeSharedVehicles.SharedVehicleModel.__ctor__(this, id)
    end
    getHandling = function (this)
      return SlipeServerVehicles.ModelHandling(this.id)
    end
    getVehicles = function (this)
      local mtaElements = SlipeMtaDefinitions.MtaShared.GetArrayFromTable(SlipeMtaDefinitions.MtaServer.GetVehiclesOfType(this.id), "MTAElement", T)
      return SlipeSharedElements.ElementManager.getInstance():CastArray(mtaElements, SlipeServerVehicles.Vehicle)
    end
    return {
      __inherits__ = function (out)
        return {
          out.Slipe.Shared.Vehicles.SharedVehicleModel
        }
      end,
      getHandling = getHandling,
      getVehicles = getVehicles,
      __ctor__ = __ctor__
    }
  end)
end)
