-- Generated by CSharp.lua Compiler
local System = System
local SlipeMtaDefinitions
local SlipeServerVehicles
System.import(function (out)
  SlipeMtaDefinitions = Slipe.MtaDefinitions
  SlipeServerVehicles = Slipe.Server.Vehicles
end)
System.namespace("Slipe.Server.Vehicles", function (namespace)
  -- <summary>
  -- A train
  -- </summary>
  namespace.class("Train", function (namespace)
    local getDirectionClockwise, setDirectionClockwise, getTrackPosition, setTrackPosition, getSpeed, setSpeed, getDerailable, setDerailable, 
    getDerailed, setDerailed, __ctor1__, __ctor2__
    -- <summary>
    -- Create a train from a model at a position
    -- </summary>
    __ctor1__ = function (this, model, position)
      SlipeServerVehicles.Vehicle.__ctor__[2](this, model, position:__clone__())
    end
    __ctor2__ = function (this, element)
      SlipeServerVehicles.Vehicle.__ctor__[1](this, element)
    end
    getDirectionClockwise = function (this)
      return SlipeMtaDefinitions.MtaShared.GetTrainDirection(this.element)
    end
    setDirectionClockwise = function (this, value)
      SlipeMtaDefinitions.MtaShared.SetTrainDirection(this.element, value)
    end
    getTrackPosition = function (this)
      return SlipeMtaDefinitions.MtaShared.GetTrainPosition(this.element)
    end
    setTrackPosition = function (this, value)
      SlipeMtaDefinitions.MtaShared.SetTrainPosition(this.element, value)
    end
    getSpeed = function (this)
      return SlipeMtaDefinitions.MtaShared.GetTrainSpeed(this.element)
    end
    setSpeed = function (this, value)
      SlipeMtaDefinitions.MtaShared.SetTrainSpeed(this.element, value)
    end
    getDerailable = function (this)
      return SlipeMtaDefinitions.MtaShared.IsTrainDerailable(this.element)
    end
    setDerailable = function (this, value)
      SlipeMtaDefinitions.MtaShared.SetTrainDerailable(this.element, value)
    end
    getDerailed = function (this)
      return SlipeMtaDefinitions.MtaShared.IsTrainDerailed(this.element)
    end
    setDerailed = function (this, value)
      SlipeMtaDefinitions.MtaShared.SetTrainDerailable(this.element, value)
    end
    return {
      __inherits__ = function (out)
        return {
          out.Slipe.Server.Vehicles.Vehicle
        }
      end,
      getDirectionClockwise = getDirectionClockwise,
      setDirectionClockwise = setDirectionClockwise,
      getTrackPosition = getTrackPosition,
      setTrackPosition = setTrackPosition,
      getSpeed = getSpeed,
      setSpeed = setSpeed,
      getDerailable = getDerailable,
      setDerailable = setDerailable,
      getDerailed = getDerailed,
      setDerailed = setDerailed,
      __ctor__ = {
        __ctor1__,
        __ctor2__
      }
    }
  end)

  -- <summary>
  -- Represents models that are trains
  -- </summary>
  namespace.class("TrainModel", function (namespace)
    local getFreightEngine, getBoxFreight, getFlatFreight, getBrownStreakEngine, getBrownStreakCarriage, getTrolly, class, __ctor__
    __ctor__ = function (this, id)
      SlipeServerVehicles.BaseVehicleModel.__ctor__(this, id)
    end
    getFreightEngine = function ()
      return class(537)
    end
    getBoxFreight = function ()
      return class(590)
    end
    getFlatFreight = function ()
      return class(569)
    end
    getBrownStreakEngine = function ()
      return class(538)
    end
    getBrownStreakCarriage = function ()
      return class(570)
    end
    getTrolly = function ()
      return class(449)
    end
    class = {
      __inherits__ = function (out)
        return {
          out.Slipe.Server.Vehicles.BaseVehicleModel
        }
      end,
      getFreightEngine = getFreightEngine,
      getBoxFreight = getBoxFreight,
      getFlatFreight = getFlatFreight,
      getBrownStreakEngine = getBrownStreakEngine,
      getBrownStreakCarriage = getBrownStreakCarriage,
      getTrolly = getTrolly,
      __ctor__ = __ctor__
    }
    return class
  end)
end)
