-- Generated by CSharp.lua Compiler
local System = System
local SlipeMtaDefinitions
local SlipeSharedElements
System.import(function (out)
  SlipeMtaDefinitions = Slipe.MtaDefinitions
  SlipeSharedElements = Slipe.Shared.Elements
end)
System.namespace("Slipe.Shared.RPC", function (namespace)
  namespace.class("BaseRPC", function (namespace)
    local GetArray, GetElementArray, GetElement
    GetArray = function (this, table, T)
      return SlipeMtaDefinitions.MtaShared.GetArrayFromTable(table, "", T)
    end
    GetElementArray = function (this, table, T)
      local mtaElements = SlipeMtaDefinitions.MtaShared.GetArrayFromTable(table, "", System.Object)

      local elements = System.Array(T):new(#mtaElements)
      for i = 0, #mtaElements - 1 do
        elements:set(i, SlipeSharedElements.ElementManager.getInstance():GetElement(mtaElements:get(i), T))
      end
      return elements
    end
    GetElement = function (this, mtaElement, T)
      return SlipeSharedElements.ElementManager.getInstance():GetElement(mtaElement, T)
    end
    return {
      GetArray = GetArray,
      GetElementArray = GetElementArray,
      GetElement = GetElement,
      __metadata__ = function (out)
        return {
          methods = {
            { "GetArray", 0x10186, GetArray, function (T) return System.Object, System.Array(T) end },
            { "GetElement", 0x10186, GetElement, function (T) return System.Object, T end },
            { "GetElementArray", 0x10186, GetElementArray, function (T) return System.Object, System.Array(T) end }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
