-- Generated by CSharp.lua Compiler
local System = System
local SlipeSharedElements
System.import(function (out)
  SlipeSharedElements = Slipe.Shared.Elements
end)
System.namespace("Slipe.Shared.Rpc", function (namespace)
  namespace.class("BasicIncomingRpc", function (namespace)
    local __ctor__
    __ctor__ = function (this, value)
      this.x = System.cast(System.Int32, value.x)
      this.name = System.cast(System.String, value.name)
      this.element = SlipeSharedElements.ElementManager.getInstance():GetElement(value.element)
    end
    return {
      __inherits__ = function (out)
        return {
          out.Slipe.Shared.Rpc.IRpc
        }
      end,
      x = 0,
      __ctor__ = __ctor__
    }
  end)
end)
