-- Generated by CSharp.lua Compiler
local System = System
System.namespace("Slipe.Shared.Rpc", function (namespace)
  namespace.class("BasicOutgoingRpc", function (namespace)
    local __ctor__
    __ctor__ = function (this, name, x, element)
      this.name = name
      this.x = x
      this.element = element:getMTAElement()
    end
    return {
      __inherits__ = function (out)
        return {
          out.Slipe.Shared.Rpc.IRpc
        }
      end,
      x = 0,
      __ctor__ = __ctor__
    }
  end)
end)
