-- Generated by CSharp.lua Compiler
local System = System
local SlipeSharedElements
System.import(function (out)
  SlipeSharedElements = Slipe.Shared.Elements
end)
System.namespace("Slipe.Shared.Elements", function (namespace)
  namespace.class("DefaultElementClassAttribute", function (namespace)
    local getElementType, __ctor1__, __ctor2__
    -- <summary>
    -- Designate a class to always be the default class when Mta elements are wrapped in Slipe classes
    -- </summary>
    __ctor1__ = function (this, type)
      System.base(this).__ctor__(this)
      this.elementType = type
    end
    -- <summary>
    -- Designate a class to always be the default class when Mta elements are wrapped in Slipe classes
    -- </summary>
    __ctor2__ = function (this, type)
      System.base(this).__ctor__(this)
      this.elementType = type:ToEnumString(SlipeSharedElements.ElementType):ToLower()
      this.elementType = this.elementType:Replace("gui", "gui-")
    end
    getElementType = function (this)
      return this.elementType
    end
    return {
      __inherits__ = function (out)
        return {
          System.Attribute
        }
      end,
      getElementType = getElementType,
      __ctor__ = {
        __ctor1__,
        __ctor2__
      }
    }
  end)
end)
