-- Generated by CSharp.lua Compiler
local System = System
local SlipeClientRendering
local SlipeMtaDefinitions
System.import(function (out)
  SlipeClientRendering = Slipe.Client.Rendering
  SlipeMtaDefinitions = Slipe.MtaDefinitions
end)
System.namespace("Slipe.Client.Rendering", function (namespace)
  -- <summary>
  -- Object containing a lot of information about various internal datum
  -- </summary>
  namespace.class("Status", function (namespace)
    local Update, __ctor__
    -- <summary>
    -- Create a new status object
    -- </summary>
    __ctor__ = function (this)
      Update(this)
    end
    -- <summary>
    -- Update the status
    -- </summary>
    Update = function (this)
      local t = SlipeMtaDefinitions.MtaShared.GetDictionaryFromTable(SlipeMtaDefinitions.MtaClient.DxGetStatus(), "System.String", "System.Dynamic")
      this.TestMode = System.cast(System.Int32, System.Enum.Parse(System.typeof(SlipeClientRendering.TestMode), t:get("TestMode")))
      this.VideoCardName = System.cast(System.String, t:get("VideoCardName"))
      this.VideoCardRAM = System.cast(System.Int32, t:get("VideoCardRAM"))
      this.VideoCardPSVersion = System.cast(System.String, t:get("VideoCardPSVersion"))
      this.VideoCardNumRenderTargets = System.cast(System.Int32, t:get("VideoCardNumRenderTargets"))
      this.VideoCardMaxAnisotropy = System.cast(System.Int32, t:get("VideoCardMaxAnisotropy"))
      this.VideoMemoryFreeForMTA = System.cast(System.Int32, t:get("VideoMemoryFreeForMTA"))
      this.VideoMemoryUsedByFonts = System.cast(System.Int32, t:get("VideoMemoryUsedByFonts"))
      this.VideoMemoryUsedByTextures = System.cast(System.Int32, t:get("VideoMemoryUsedByTextures"))
      this.VideoMemoryUsedByRenderTargets = System.cast(System.Int32, t:get("VideoMemoryUsedByRenderTargets"))
      this.SettingWindowed = System.cast(System.Boolean, t:get("SettingWindowed"))
      this.SettingFullScreenStyle = System.cast(System.Int32, t:get("SettingFullScreenStyle"))
      this.SettingFXQuality = System.cast(System.Int32, t:get("SettingFXQuality"))
      this.SettingDrawDistance = System.cast(System.Int32, t:get("SettingDrawDistance"))
      this.SettingVolumetricShadows = System.cast(System.Boolean, t:get("SettingVolumetricShadows"))
      this.SettingStreamingVideoMemoryForGTA = System.cast(System.Int32, t:get("SettingStreamingVideoMemoryForGTA"))
      this.SettingAnisotropicFiltering = System.cast(System.Int32, t:get("SettingAnisotropicFiltering"))
      this.SettingAntiAliasing = System.cast(System.Int32, t:get("SettingAntiAliasing"))
      this.SettingHeatHaze = System.cast(System.Boolean, t:get("SettingHeatHaze"))
      this.SettingGrassEffect = System.cast(System.Boolean, t:get("SettingGrassEffect"))
      this.Setting32BitColor = System.cast(System.Boolean, t:get("Setting32BitColor"))
      this.SettingHUDMatchAspectRatio = System.cast(System.Boolean, t:get("SettingHUDMatchAspectRatio"))
      this.SettingAspectRatio = System.cast(System.String, t:get("SettingAspectRatio"))
      this.SettingFOV = System.cast(System.Int32, t:get("SettingFOV"))
      this.SettingHighDetailVehicles = System.cast(System.Boolean, t:get("SettingHighDetailVehicles"))
      this.AllowScreenUpload = System.cast(System.Boolean, t:get("AllowScreenUpload"))
      this.DepthBufferFormat = System.cast(System.String, t:get("DepthBufferFormat"))
      this.UsingDepthBuffer = System.cast(System.Boolean, t:get("UsingDepthBuffer"))
    end
    return {
      TestMode = 0,
      VideoCardRAM = 0,
      VideoCardNumRenderTargets = 0,
      VideoCardMaxAnisotropy = 0,
      VideoMemoryFreeForMTA = 0,
      VideoMemoryUsedByFonts = 0,
      VideoMemoryUsedByTextures = 0,
      VideoMemoryUsedByRenderTargets = 0,
      SettingWindowed = false,
      SettingFullScreenStyle = 0,
      SettingFXQuality = 0,
      SettingDrawDistance = 0,
      SettingVolumetricShadows = false,
      SettingStreamingVideoMemoryForGTA = 0,
      SettingAnisotropicFiltering = 0,
      SettingAntiAliasing = 0,
      SettingHeatHaze = false,
      SettingGrassEffect = false,
      Setting32BitColor = false,
      SettingHUDMatchAspectRatio = false,
      SettingFOV = 0,
      SettingHighDetailVehicles = false,
      AllowScreenUpload = false,
      UsingDepthBuffer = false,
      Update = Update,
      __ctor__ = __ctor__
    }
  end)
end)
