-- Generated by CSharp.lua Compiler
local System = System
local SlipeMtaDefinitions
System.import(function (out)
  SlipeMtaDefinitions = Slipe.MtaDefinitions
end)
System.namespace("Slipe.Client.Sounds", function (namespace)
  -- <summary>
  -- Represents different sound properties
  -- </summary>
  namespace.class("SoundProperties", function (namespace)
    local getSampleRate, setSampleRate, getTempo, setTempo, getPitch, setPitch, getReverse, setReverse, 
    __ctor__
    __ctor__ = function (this, sound)
      this.sound = sound
    end
    getSampleRate = function (this)
      sampleRate, _, _, _ = SlipeMtaDefinitions.MtaClient.GetSoundProperties(this.sound:getMTAElement()):Deconstruct()
      return sampleRate
    end
    setSampleRate = function (this, value)
      SlipeMtaDefinitions.MtaClient.SetSoundProperties(this.sound:getMTAElement(), value, getTempo(this), getPitch(this), getReverse(this))
    end
    getTempo = function (this)
      _, tempo, _, _ = SlipeMtaDefinitions.MtaClient.GetSoundProperties(this.sound:getMTAElement()):Deconstruct()
      return tempo
    end
    setTempo = function (this, value)
      SlipeMtaDefinitions.MtaClient.SetSoundProperties(this.sound:getMTAElement(), getSampleRate(this), value, getPitch(this), getReverse(this))
    end
    getPitch = function (this)
      _, _, pitch, _ = SlipeMtaDefinitions.MtaClient.GetSoundProperties(this.sound:getMTAElement()):Deconstruct()
      return pitch
    end
    setPitch = function (this, value)
      SlipeMtaDefinitions.MtaClient.SetSoundProperties(this.sound:getMTAElement(), getSampleRate(this), getTempo(this), value, getReverse(this))
    end
    getReverse = function (this)
      _, _, _, reverse = SlipeMtaDefinitions.MtaClient.GetSoundProperties(this.sound:getMTAElement()):Deconstruct()
      return reverse
    end
    setReverse = function (this, value)
      SlipeMtaDefinitions.MtaClient.SetSoundProperties(this.sound:getMTAElement(), getSampleRate(this), getTempo(this), getPitch(this), value)
    end
    return {
      getSampleRate = getSampleRate,
      setSampleRate = setSampleRate,
      getTempo = getTempo,
      setTempo = setTempo,
      getPitch = getPitch,
      setPitch = setPitch,
      getReverse = getReverse,
      setReverse = setReverse,
      __ctor__ = __ctor__
    }
  end)
end)
