-- Generated by CSharp.lua Compiler
local System = System
local SlipeMtaDefinitions
System.import(function (out)
  SlipeMtaDefinitions = Slipe.MtaDefinitions
end)
System.namespace("Slipe.Client.Sounds", function (namespace)
  -- <summary>
  -- Represents sound meta data
  -- </summary>
  namespace.class("SoundMeta", function (namespace)
    local getTitle, getArtist, getAlbum, getGenre, getYear, getComment, getTrack, getComposer, 
    getCopyright, getSubtitle, getAlbumArtist, getStreamName, getStreamTitle, __ctor__
    __ctor__ = function (this, sound)
      this.sound = sound
    end
    getTitle = function (this)
      local default, extern = System.try(function ()
        return true, SlipeMtaDefinitions.MtaClient.GetSoundMetaTags(this.sound:getMTAElement(), "title")
      end, function (default)
        if System.is(default, SlipeMtaDefinitions.MtaException) then
          return true, nil
        else
          return 1, default
        end
      end)
      if default then
        return extern
      end
    end
    getArtist = function (this)
      local default, extern = System.try(function ()
        return true, SlipeMtaDefinitions.MtaClient.GetSoundMetaTags(this.sound:getMTAElement(), "artist")
      end, function (default)
        if System.is(default, SlipeMtaDefinitions.MtaException) then
          return true, nil
        else
          return 1, default
        end
      end)
      if default then
        return extern
      end
    end
    getAlbum = function (this)
      local default, extern = System.try(function ()
        return true, SlipeMtaDefinitions.MtaClient.GetSoundMetaTags(this.sound:getMTAElement(), "album")
      end, function (default)
        if System.is(default, SlipeMtaDefinitions.MtaException) then
          return true, nil
        else
          return 1, default
        end
      end)
      if default then
        return extern
      end
    end
    getGenre = function (this)
      local default, extern = System.try(function ()
        return true, SlipeMtaDefinitions.MtaClient.GetSoundMetaTags(this.sound:getMTAElement(), "genre")
      end, function (default)
        if System.is(default, SlipeMtaDefinitions.MtaException) then
          return true, nil
        else
          return 1, default
        end
      end)
      if default then
        return extern
      end
    end
    getYear = function (this)
      local default, extern = System.try(function ()
        return true, SlipeMtaDefinitions.MtaClient.GetSoundMetaTags(this.sound:getMTAElement(), "year")
      end, function (default)
        if System.is(default, SlipeMtaDefinitions.MtaException) then
          return true, nil
        else
          return 1, default
        end
      end)
      if default then
        return extern
      end
    end
    getComment = function (this)
      local default, extern = System.try(function ()
        return true, SlipeMtaDefinitions.MtaClient.GetSoundMetaTags(this.sound:getMTAElement(), "comment")
      end, function (default)
        if System.is(default, SlipeMtaDefinitions.MtaException) then
          return true, nil
        else
          return 1, default
        end
      end)
      if default then
        return extern
      end
    end
    getTrack = function (this)
      local default, extern = System.try(function ()
        return true, SlipeMtaDefinitions.MtaClient.GetSoundMetaTags(this.sound:getMTAElement(), "track")
      end, function (default)
        if System.is(default, SlipeMtaDefinitions.MtaException) then
          return true, nil
        else
          return 1, default
        end
      end)
      if default then
        return extern
      end
    end
    getComposer = function (this)
      local default, extern = System.try(function ()
        return true, SlipeMtaDefinitions.MtaClient.GetSoundMetaTags(this.sound:getMTAElement(), "composer")
      end, function (default)
        if System.is(default, SlipeMtaDefinitions.MtaException) then
          return true, nil
        else
          return 1, default
        end
      end)
      if default then
        return extern
      end
    end
    getCopyright = function (this)
      local default, extern = System.try(function ()
        return true, SlipeMtaDefinitions.MtaClient.GetSoundMetaTags(this.sound:getMTAElement(), "copyright")
      end, function (default)
        if System.is(default, SlipeMtaDefinitions.MtaException) then
          return true, nil
        else
          return 1, default
        end
      end)
      if default then
        return extern
      end
    end
    getSubtitle = function (this)
      local default, extern = System.try(function ()
        return true, SlipeMtaDefinitions.MtaClient.GetSoundMetaTags(this.sound:getMTAElement(), "subtitle")
      end, function (default)
        if System.is(default, SlipeMtaDefinitions.MtaException) then
          return true, nil
        else
          return 1, default
        end
      end)
      if default then
        return extern
      end
    end
    getAlbumArtist = function (this)
      local default, extern = System.try(function ()
        return true, SlipeMtaDefinitions.MtaClient.GetSoundMetaTags(this.sound:getMTAElement(), "album_artist")
      end, function (default)
        if System.is(default, SlipeMtaDefinitions.MtaException) then
          return true, nil
        else
          return 1, default
        end
      end)
      if default then
        return extern
      end
    end
    getStreamName = function (this)
      local default, extern = System.try(function ()
        return true, SlipeMtaDefinitions.MtaClient.GetSoundMetaTags(this.sound:getMTAElement(), "stream_name")
      end, function (default)
        if System.is(default, SlipeMtaDefinitions.MtaException) then
          return true, nil
        else
          return 1, default
        end
      end)
      if default then
        return extern
      end
    end
    getStreamTitle = function (this)
      local default, extern = System.try(function ()
        return true, SlipeMtaDefinitions.MtaClient.GetSoundMetaTags(this.sound:getMTAElement(), "stream_title")
      end, function (default)
        if System.is(default, SlipeMtaDefinitions.MtaException) then
          return true, nil
        else
          return 1, default
        end
      end)
      if default then
        return extern
      end
    end
    return {
      getTitle = getTitle,
      getArtist = getArtist,
      getAlbum = getAlbum,
      getGenre = getGenre,
      getYear = getYear,
      getComment = getComment,
      getTrack = getTrack,
      getComposer = getComposer,
      getCopyright = getCopyright,
      getSubtitle = getSubtitle,
      getAlbumArtist = getAlbumArtist,
      getStreamName = getStreamName,
      getStreamTitle = getStreamTitle,
      __ctor__ = __ctor__
    }
  end)
end)
