-- Generated by CSharp.lua Compiler
local System = System
local SlipeClientSounds
local SlipeMtaDefinitions
local SlipeSharedElements
local SystemNumerics
System.import(function (out)
  SlipeClientSounds = Slipe.Client.Sounds
  SlipeMtaDefinitions = Slipe.MtaDefinitions
  SlipeSharedElements = Slipe.Shared.Elements
  SystemNumerics = System.Numerics
end)
System.namespace("Slipe.Client.Sounds", function (namespace)
  -- <summary>
  -- Represents a sound played at a certain location in the world
  -- </summary>
  namespace.class("WorldSound", function (namespace)
    local getPosition, setPosition, getDimension, setDimension, getMaxDistance, setMaxDistance, getMinDistance, setMinDistance, 
    getPanningEnabled, setPanningEnabled, AttachTo, AttachTo1, Detach, getToAttached, getIsAttached, __ctor1__, 
    __ctor2__, __ctor3__, __ctor4__, __ctor5__
    __ctor1__ = function (this, element)
      SlipeClientSounds.Sound.__ctor__[1](this, element)
    end
    -- <summary>
    -- Create a sound in the world at a certain position
    -- </summary>
    __ctor2__ = function (this, pathOrUrl, position, looped, throttled)
      __ctor1__(this, SlipeMtaDefinitions.MtaClient.PlaySound3D(pathOrUrl, position.X, position.Y, position.Z, looped, throttled))
    end
    -- <summary>
    -- Create a GTA Sfx at a 3D position in the world
    -- </summary>
    __ctor3__ = function (this, container, bankId, soundId, position, looped)
      __ctor1__(this, SlipeMtaDefinitions.MtaClient.PlaySFX3D(container:ToEnumString(SlipeClientSounds.SoundContainer):ToLower(), bankId, soundId, position.X, position.Y, position.Z, looped))
    end
    -- <summary>
    -- Create a GTA radio station sound at a 3D position in the world
    -- </summary>
    __ctor4__ = function (this, station, trackId, position, looped)
      __ctor1__(this, SlipeMtaDefinitions.MtaClient.PlaySFX3D("radio", SlipeMtaDefinitions.MtaClient.GetRadioChannelName(station), trackId, position.X, position.Y, position.Z, looped))
    end
    -- <summary>
    -- Create an extra GTA radio station sound at a 3D position in the world
    -- </summary>
    __ctor5__ = function (this, station, trackId, position, looped)
      __ctor1__(this, SlipeMtaDefinitions.MtaClient.PlaySFX3D("radio", station:ToEnumString(SlipeClientSounds.ExtraStations), trackId, position.X, position.Y, position.Z, looped))
    end
    getPosition = function (this)
      local position = SlipeMtaDefinitions.MtaShared.GetElementPosition(this.element)
      return SystemNumerics.Vector3(position[1], position[2], position[3])
    end
    setPosition = function (this, value)
      SlipeMtaDefinitions.MtaShared.SetElementPosition(this.element, value.X, value.Y, value.Z, false)
    end
    getDimension = function (this)
      return SlipeMtaDefinitions.MtaShared.GetElementDimension(this.element)
    end
    setDimension = function (this, value)
      SlipeMtaDefinitions.MtaShared.SetElementDimension(this.element, value)
    end
    getMaxDistance = function (this)
      return SlipeMtaDefinitions.MtaClient.GetSoundMaxDistance(this.element)
    end
    setMaxDistance = function (this, value)
      SlipeMtaDefinitions.MtaClient.SetSoundMaxDistance(this.element, value)
    end
    getMinDistance = function (this)
      return SlipeMtaDefinitions.MtaClient.GetSoundMinDistance(this.element)
    end
    setMinDistance = function (this, value)
      SlipeMtaDefinitions.MtaClient.SetSoundMinDistance(this.element, value)
    end
    getPanningEnabled = function (this)
      return SlipeMtaDefinitions.MtaClient.IsSoundPanningEnabled(this.element)
    end
    setPanningEnabled = function (this, value)
      SlipeMtaDefinitions.MtaClient.SetSoundPanningEnabled(this.element, value)
    end
    -- <summary>
    -- Attach this attachable to a Physical Element with an offset
    -- </summary>
    AttachTo = function (this, toElement, offset)
      SlipeMtaDefinitions.MtaShared.AttachElements(this.element, toElement:getMTAElement(), offset.X, offset.Y, offset.Z, 0, 0, 0)
    end
    -- <summary>
    -- Attach this attachable to a Physical Element without any offset
    -- </summary>
    AttachTo1 = function (this, toElement)
      AttachTo(this, toElement, SystemNumerics.Vector3.getZero())
    end
    -- <summary>
    -- Detach this attachable
    -- </summary>
    Detach = function (this)
      SlipeMtaDefinitions.MtaShared.DetachElements(this.element)
    end
    getToAttached = function (this)
      return SlipeSharedElements.ElementManager.getInstance():GetElement(SlipeMtaDefinitions.MtaShared.GetElementAttachedTo(this.element), SlipeSharedElements.PhysicalElement)
    end
    getIsAttached = function (this)
      return SlipeMtaDefinitions.MtaShared.IsElementAttached(this.element)
    end
    return {
      __inherits__ = function (out)
        return {
          out.Slipe.Client.Sounds.Sound
        }
      end,
      getPosition = getPosition,
      setPosition = setPosition,
      getDimension = getDimension,
      setDimension = setDimension,
      getMaxDistance = getMaxDistance,
      setMaxDistance = setMaxDistance,
      getMinDistance = getMinDistance,
      setMinDistance = setMinDistance,
      getPanningEnabled = getPanningEnabled,
      setPanningEnabled = setPanningEnabled,
      AttachTo = AttachTo,
      AttachTo1 = AttachTo1,
      Detach = Detach,
      getToAttached = getToAttached,
      getIsAttached = getIsAttached,
      __ctor__ = {
        __ctor1__,
        __ctor2__,
        __ctor3__,
        __ctor4__,
        __ctor5__
      }
    }
  end)
end)
