-- Generated by CSharp.lua Compiler
local System = System
System.namespace("Slipe.Client.Peds", function (namespace)
  -- <summary>
  -- Represents a PedVoice group and name
  -- </summary>
  namespace.struct("PedVoice", function (namespace)
    local getDISABLED, getGEN_BBDYG1, getGEN_BBDYG2, getGEN_BFORI, getGEN_BFOST, getGEN_BFYBE, getGEN_BFYBU, getGEN_BFYCRP, 
    getGEN_BFYPRO, getGEN_BFYRI, getGEN_BFYST, getGEN_BIKDRUG, getGEN_BIKERA, getGEN_BIKERB, getGEN_BMOCD, getGEN_BMORI, 
    getGEN_BMOSEC, getGEN_BMOST, getGEN_BMOTR1, getGEN_BMYAP, getGEN_BMYBE, getGEN_BMYBOUN, getGEN_BMYBOX, getGEN_BMYBU, 
    getGEN_BMYCG, getGEN_BMYCON, getGEN_BMYCR, getGEN_BMYDJ, getGEN_BMYDRUG, getGEN_BMYMOUN, getGEN_BMYPOL1, getGEN_BMYPOL2, 
    getGEN_BMYRI, getGEN_BMYST, getGEN_BYMPI, getGEN_CWFOFR, getGEN_CWFOHB, getGEN_CWFYFR1, getGEN_CWFYFR2, getGEN_CWFYHB1, 
    getGEN_CWMOFR1, getGEN_CWMOHB1, getGEN_CWMOHB2, getGEN_CWMYFR, getGEN_CWMYHB1, getGEN_CWMYHB2, getGEN_DNFOLC1, getGEN_DNFOLC2, 
    getGEN_DNFYLC, getGEN_DNMOLC1, getGEN_DNMOLC2, getGEN_DNMYLC, getGEN_DWFOLC, getGEN_DWFYLC1, getGEN_DWFYLC2, getGEN_DWMOLC1, 
    getGEN_DWMOLC2, getGEN_DWMYLC1, getGEN_DWMYLC2, getGEN_HFORI, getGEN_HFOST, getGEN_HFYBE, getGEN_HFYPRO, getGEN_HFYRI, 
    getGEN_HFYST, getGEN_HMORI, getGEN_HMOST, getGEN_HMYBE, getGEN_HMYCM, getGEN_HMYCR, getGEN_HMYDRUG, getGEN_HMYRI, 
    getGEN_HMYST, getGEN_IMYST, getGEN_IRFYST, getGEN_IRMYST, getGEN_MAFFA, getGEN_MAFFB, getGEN_MALE01, getGEN_NOVOICE, 
    getGEN_OFORI, getGEN_OFOST, getGEN_OFYRI, getGEN_OFYST, getGEN_OMOBOAT, getGEN_OMOKUNG, getGEN_OMORI, getGEN_OMOST, 
    getGEN_OMYRI, getGEN_OMYST, getGEN_SBFORI, getGEN_SBFOST, getGEN_SBFYPRO, getGEN_SBFYRI, getGEN_SBFYST, getGEN_SBFYSTR, 
    getGEN_SBMOCD, getGEN_SBMORI, getGEN_SBMOST, getGEN_SBMOTR1, getGEN_SBMOTR2, getGEN_SBMYCR, getGEN_SBMYRI, getGEN_SBMYST, 
    getGEN_SBMYTR3, getGEN_SFYPRO, getGEN_SHFYPRO, getGEN_SHMYCR, getGEN_SMYST, getGEN_SMYST2, getGEN_SOFORI, getGEN_SOFOST, 
    getGEN_SOFYBU, getGEN_SOFYRI, getGEN_SOFYST, getGEN_SOMOBU, getGEN_SOMORI, getGEN_SOMOST, getGEN_SOMYAP, getGEN_SOMYBU, 
    getGEN_SOMYRI, getGEN_SOMYST, getGEN_SWFOPRO, getGEN_SWFORI, getGEN_SWFOST, getGEN_SWFYRI, getGEN_SWFYST, getGEN_SWFYSTR, 
    getGEN_SWMOCD, getGEN_SWMORI, getGEN_SWMOST, getGEN_SWMOTR1, getGEN_SWMOTR2, getGEN_SWMOTR3, getGEN_SWMOTR4, getGEN_SWMOTR5, 
    getGEN_SWMYCR, getGEN_SWMYHP1, getGEN_SWMYHP2, getGEN_SWMYRI, getGEN_SWMYST, getGEN_VBFYPRO, getGEN_VBFYST2, getGEN_VBMOCD, 
    getGEN_VBMYCR, getGEN_VBMYELV, getGEN_VHFYPRO, getGEN_VHFYST3, getGEN_VHMYCR, getGEN_VHMYELV, getGEN_VIMYELV, getGEN_VWFYPRO, 
    getGEN_VWFYST1, getGEN_VWFYWAI, getGEN_VWMOTR1, getGEN_VWMOTR2, getGEN_VWMYAP, getGEN_VWMYBJD, getGEN_VWMYCD, getGEN_VWMYCR, 
    getGEN_WFOPJ, getGEN_WFORI, getGEN_WFOST, getGEN_WFYBE, getGEN_WFYBU, getGEN_WFYCRK, getGEN_WFYCRP, getGEN_WFYJG, 
    getGEN_WFYLG, getGEN_WFYPRO, getGEN_WFYRI, getGEN_WFYRO, getGEN_WFYST, getGEN_WFYSTEW, getGEN_WMOMIB, getGEN_WMOPJ, 
    getGEN_WMOPREA, getGEN_WMORI, getGEN_WMOSCI, getGEN_WMOST, getGEN_WMOTR1, getGEN_WMYBE, getGEN_WMYBMX, getGEN_WMYBOUN, 
    getGEN_WMYBOX, getGEN_WMYBP, getGEN_WMYBU, getGEN_WMYCD1, getGEN_WMYCD2, getGEN_WMYCH, getGEN_WMYCON, getGEN_WMYCONB, 
    getGEN_WMYCR, getGEN_WMYDRUG, class, __ctor1__, __ctor2__
    __ctor1__ = function (this)
    end
    -- <summary>
    -- Build a ped voice from a group and name
    -- </summary>
    __ctor2__ = function (this, group, name)
      this.Group = group
      this.Name = name
    end
    getDISABLED = function ()
      return System.new(class, 2, "PED_TYPE_DISABLED")
    end
    getGEN_BBDYG1 = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_BBDYG1")
    end
    getGEN_BBDYG2 = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_BBDYG2")
    end
    getGEN_BFORI = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_BFORI")
    end
    getGEN_BFOST = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_BFOST")
    end
    getGEN_BFYBE = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_BFYBE")
    end
    getGEN_BFYBU = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_BFYBU")
    end
    getGEN_BFYCRP = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_BFYCRP")
    end
    getGEN_BFYPRO = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_BFYPRO")
    end
    getGEN_BFYRI = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_BFYRI")
    end
    getGEN_BFYST = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_BFYST")
    end
    getGEN_BIKDRUG = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_BIKDRUG")
    end
    getGEN_BIKERA = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_BIKERA")
    end
    getGEN_BIKERB = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_BIKERB")
    end
    getGEN_BMOCD = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_BMOCD")
    end
    getGEN_BMORI = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_BMORI")
    end
    getGEN_BMOSEC = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_BMOSEC")
    end
    getGEN_BMOST = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_BMOST")
    end
    getGEN_BMOTR1 = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_BMOTR1")
    end
    getGEN_BMYAP = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_BMYAP")
    end
    getGEN_BMYBE = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_BMYBE")
    end
    getGEN_BMYBOUN = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_BMYBOUN")
    end
    getGEN_BMYBOX = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_BMYBOX")
    end
    getGEN_BMYBU = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_BMYBU")
    end
    getGEN_BMYCG = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_BMYCG")
    end
    getGEN_BMYCON = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_BMYCON")
    end
    getGEN_BMYCR = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_BMYCR")
    end
    getGEN_BMYDJ = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_BMYDJ")
    end
    getGEN_BMYDRUG = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_BMYDRUG")
    end
    getGEN_BMYMOUN = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_BMYMOUN")
    end
    getGEN_BMYPOL1 = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_BMYPOL1")
    end
    getGEN_BMYPOL2 = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_BMYPOL2")
    end
    getGEN_BMYRI = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_BMYRI")
    end
    getGEN_BMYST = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_BMYST")
    end
    getGEN_BYMPI = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_BYMPI")
    end
    getGEN_CWFOFR = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_CWFOFR")
    end
    getGEN_CWFOHB = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_CWFOHB")
    end
    getGEN_CWFYFR1 = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_CWFYFR1")
    end
    getGEN_CWFYFR2 = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_CWFYFR2")
    end
    getGEN_CWFYHB1 = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_CWFYHB1")
    end
    getGEN_CWMOFR1 = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_CWMOFR1")
    end
    getGEN_CWMOHB1 = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_CWMOHB1")
    end
    getGEN_CWMOHB2 = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_CWMOHB2")
    end
    getGEN_CWMYFR = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_CWMYFR")
    end
    getGEN_CWMYHB1 = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_CWMYHB1")
    end
    getGEN_CWMYHB2 = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_CWMYHB2")
    end
    getGEN_DNFOLC1 = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_DNFOLC1")
    end
    getGEN_DNFOLC2 = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_DNFOLC2")
    end
    getGEN_DNFYLC = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_DNFYLC")
    end
    getGEN_DNMOLC1 = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_DNMOLC1")
    end
    getGEN_DNMOLC2 = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_DNMOLC2")
    end
    getGEN_DNMYLC = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_DNMYLC")
    end
    getGEN_DWFOLC = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_DWFOLC")
    end
    getGEN_DWFYLC1 = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_DWFYLC1")
    end
    getGEN_DWFYLC2 = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_DWFYLC2")
    end
    getGEN_DWMOLC1 = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_DWMOLC1")
    end
    getGEN_DWMOLC2 = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_DWMOLC2")
    end
    getGEN_DWMYLC1 = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_DWMYLC1")
    end
    getGEN_DWMYLC2 = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_DWMYLC2")
    end
    getGEN_HFORI = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_HFORI")
    end
    getGEN_HFOST = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_HFOST")
    end
    getGEN_HFYBE = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_HFYBE")
    end
    getGEN_HFYPRO = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_HFYPRO")
    end
    getGEN_HFYRI = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_HFYRI")
    end
    getGEN_HFYST = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_HFYST")
    end
    getGEN_HMORI = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_HMORI")
    end
    getGEN_HMOST = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_HMOST")
    end
    getGEN_HMYBE = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_HMYBE")
    end
    getGEN_HMYCM = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_HMYCM")
    end
    getGEN_HMYCR = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_HMYCR")
    end
    getGEN_HMYDRUG = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_HMYDRUG")
    end
    getGEN_HMYRI = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_HMYRI")
    end
    getGEN_HMYST = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_HMYST")
    end
    getGEN_IMYST = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_IMYST")
    end
    getGEN_IRFYST = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_IRFYST")
    end
    getGEN_IRMYST = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_IRMYST")
    end
    getGEN_MAFFA = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_MAFFA")
    end
    getGEN_MAFFB = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_MAFFB")
    end
    getGEN_MALE01 = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_MALE01")
    end
    getGEN_NOVOICE = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_NOVOICE")
    end
    getGEN_OFORI = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_OFORI")
    end
    getGEN_OFOST = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_OFOST")
    end
    getGEN_OFYRI = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_OFYRI")
    end
    getGEN_OFYST = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_OFYST")
    end
    getGEN_OMOBOAT = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_OMOBOAT")
    end
    getGEN_OMOKUNG = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_OMOKUNG")
    end
    getGEN_OMORI = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_OMORI")
    end
    getGEN_OMOST = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_OMOST")
    end
    getGEN_OMYRI = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_OMYRI")
    end
    getGEN_OMYST = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_OMYST")
    end
    getGEN_SBFORI = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_SBFORI")
    end
    getGEN_SBFOST = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_SBFOST")
    end
    getGEN_SBFYPRO = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_SBFYPRO")
    end
    getGEN_SBFYRI = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_SBFYRI")
    end
    getGEN_SBFYST = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_SBFYST")
    end
    getGEN_SBFYSTR = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_SBFYSTR")
    end
    getGEN_SBMOCD = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_SBMOCD")
    end
    getGEN_SBMORI = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_SBMORI")
    end
    getGEN_SBMOST = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_SBMOST")
    end
    getGEN_SBMOTR1 = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_SBMOTR1")
    end
    getGEN_SBMOTR2 = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_SBMOTR2")
    end
    getGEN_SBMYCR = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_SBMYCR")
    end
    getGEN_SBMYRI = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_SBMYRI")
    end
    getGEN_SBMYST = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_SBMYST")
    end
    getGEN_SBMYTR3 = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_SBMYTR3")
    end
    getGEN_SFYPRO = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_SFYPRO")
    end
    getGEN_SHFYPRO = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_SHFYPRO")
    end
    getGEN_SHMYCR = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_SHMYCR")
    end
    getGEN_SMYST = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_SMYST")
    end
    getGEN_SMYST2 = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_SMYST2")
    end
    getGEN_SOFORI = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_SOFORI")
    end
    getGEN_SOFOST = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_SOFOST")
    end
    getGEN_SOFYBU = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_SOFYBU")
    end
    getGEN_SOFYRI = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_SOFYRI")
    end
    getGEN_SOFYST = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_SOFYST")
    end
    getGEN_SOMOBU = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_SOMOBU")
    end
    getGEN_SOMORI = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_SOMORI")
    end
    getGEN_SOMOST = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_SOMOST")
    end
    getGEN_SOMYAP = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_SOMYAP")
    end
    getGEN_SOMYBU = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_SOMYBU")
    end
    getGEN_SOMYRI = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_SOMYRI")
    end
    getGEN_SOMYST = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_SOMYST")
    end
    getGEN_SWFOPRO = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_SWFOPRO")
    end
    getGEN_SWFORI = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_SWFORI")
    end
    getGEN_SWFOST = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_SWFOST")
    end
    getGEN_SWFYRI = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_SWFYRI")
    end
    getGEN_SWFYST = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_SWFYST")
    end
    getGEN_SWFYSTR = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_SWFYSTR")
    end
    getGEN_SWMOCD = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_SWMOCD")
    end
    getGEN_SWMORI = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_SWMORI")
    end
    getGEN_SWMOST = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_SWMOST")
    end
    getGEN_SWMOTR1 = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_SWMOTR1")
    end
    getGEN_SWMOTR2 = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_SWMOTR2")
    end
    getGEN_SWMOTR3 = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_SWMOTR3")
    end
    getGEN_SWMOTR4 = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_SWMOTR4")
    end
    getGEN_SWMOTR5 = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_SWMOTR5")
    end
    getGEN_SWMYCR = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_SWMYCR")
    end
    getGEN_SWMYHP1 = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_SWMYHP1")
    end
    getGEN_SWMYHP2 = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_SWMYHP2")
    end
    getGEN_SWMYRI = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_SWMYRI")
    end
    getGEN_SWMYST = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_SWMYST")
    end
    getGEN_VBFYPRO = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_VBFYPRO")
    end
    getGEN_VBFYST2 = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_VBFYST2")
    end
    getGEN_VBMOCD = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_VBMOCD")
    end
    getGEN_VBMYCR = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_VBMYCR")
    end
    getGEN_VBMYELV = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_VBMYELV")
    end
    getGEN_VHFYPRO = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_VHFYPRO")
    end
    getGEN_VHFYST3 = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_VHFYST3")
    end
    getGEN_VHMYCR = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_VHMYCR")
    end
    getGEN_VHMYELV = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_VHMYELV")
    end
    getGEN_VIMYELV = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_VIMYELV")
    end
    getGEN_VWFYPRO = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_VWFYPRO")
    end
    getGEN_VWFYST1 = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_VWFYST1")
    end
    getGEN_VWFYWAI = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_VWFYWAI")
    end
    getGEN_VWMOTR1 = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_VWMOTR1")
    end
    getGEN_VWMOTR2 = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_VWMOTR2")
    end
    getGEN_VWMYAP = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_VWMYAP")
    end
    getGEN_VWMYBJD = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_VWMYBJD")
    end
    getGEN_VWMYCD = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_VWMYCD")
    end
    getGEN_VWMYCR = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_VWMYCR")
    end
    getGEN_WFOPJ = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_WFOPJ")
    end
    getGEN_WFORI = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_WFORI")
    end
    getGEN_WFOST = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_WFOST")
    end
    getGEN_WFYBE = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_WFYBE")
    end
    getGEN_WFYBU = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_WFYBU")
    end
    getGEN_WFYCRK = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_WFYCRK")
    end
    getGEN_WFYCRP = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_WFYCRP")
    end
    getGEN_WFYJG = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_WFYJG")
    end
    getGEN_WFYLG = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_WFYLG")
    end
    getGEN_WFYPRO = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_WFYPRO")
    end
    getGEN_WFYRI = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_WFYRI")
    end
    getGEN_WFYRO = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_WFYRO")
    end
    getGEN_WFYST = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_WFYST")
    end
    getGEN_WFYSTEW = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_WFYSTEW")
    end
    getGEN_WMOMIB = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_WMOMIB")
    end
    getGEN_WMOPJ = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_WMOPJ")
    end
    getGEN_WMOPREA = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_WMOPREA")
    end
    getGEN_WMORI = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_WMORI")
    end
    getGEN_WMOSCI = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_WMOSCI")
    end
    getGEN_WMOST = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_WMOST")
    end
    getGEN_WMOTR1 = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_WMOTR1")
    end
    getGEN_WMYBE = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_WMYBE")
    end
    getGEN_WMYBMX = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_WMYBMX")
    end
    getGEN_WMYBOUN = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_WMYBOUN")
    end
    getGEN_WMYBOX = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_WMYBOX")
    end
    getGEN_WMYBP = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_WMYBP")
    end
    getGEN_WMYBU = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_WMYBU")
    end
    getGEN_WMYCD1 = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_WMYCD1")
    end
    getGEN_WMYCD2 = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_WMYCD2")
    end
    getGEN_WMYCH = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_WMYCH")
    end
    getGEN_WMYCON = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_WMYCON")
    end
    getGEN_WMYCONB = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_WMYCONB")
    end
    getGEN_WMYCR = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_WMYCR")
    end
    getGEN_WMYDRUG = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_WMYDRUG")
    end
    -- too many local variables (limit is 200)
    local const = {}
    const.getGEN_WMYGAR = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_WMYGAR")
    end
    const.getGEN_WMYGOL1 = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_WMYGOL1")
    end
    const.getGEN_WMYGOL2 = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_WMYGOL2")
    end
    const.getGEN_WMYJG = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_WMYJG")
    end
    const.getGEN_WMYLG = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_WMYLG")
    end
    const.getGEN_WMYMECH = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_WMYMECH")
    end
    const.getGEN_WMYMOUN = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_WMYMOUN")
    end
    const.getGEN_WMYPLT = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_WMYPLT")
    end
    const.getGEN_WMYRI = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_WMYRI")
    end
    const.getGEN_WMYRO = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_WMYRO")
    end
    const.getGEN_WMYSGRD = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_WMYSGRD")
    end
    const.getGEN_WMYSKAT = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_WMYSKAT")
    end
    const.getGEN_WMYST = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_WMYST")
    end
    const.getGEN_WMYTX1 = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_WMYTX1")
    end
    const.getGEN_WMYTX2 = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_WMYTX2")
    end
    const.getGEN_WMYVA = function ()
      return System.new(class, 2, "PED_TYPE_GEN", "VOICE_GEN_WMYVA")
    end
    const.getEMG_ARMY1 = function ()
      return System.new(class, 2, "PED_TYPE_EMG", "VOICE_EMG_ARMY1")
    end
    const.getEMG_ARMY2 = function ()
      return System.new(class, 2, "PED_TYPE_EMG", "VOICE_EMG_ARMY2")
    end
    const.getEMG_ARMY3 = function ()
      return System.new(class, 2, "PED_TYPE_EMG", "VOICE_EMG_ARMY3")
    end
    const.getEMG_EMT1 = function ()
      return System.new(class, 2, "PED_TYPE_EMG", "VOICE_EMG_EMT1")
    end
    const.getEMG_EMT2 = function ()
      return System.new(class, 2, "PED_TYPE_EMG", "VOICE_EMG_EMT2")
    end
    const.getEMG_EMT3 = function ()
      return System.new(class, 2, "PED_TYPE_EMG", "VOICE_EMG_EMT3")
    end
    const.getEMG_EMT4 = function ()
      return System.new(class, 2, "PED_TYPE_EMG", "VOICE_EMG_EMT4")
    end
    const.getEMG_EMT5 = function ()
      return System.new(class, 2, "PED_TYPE_EMG", "VOICE_EMG_EMT5")
    end
    const.getEMG_FBI2 = function ()
      return System.new(class, 2, "PED_TYPE_EMG", "VOICE_EMG_FBI2")
    end
    const.getEMG_FBI3 = function ()
      return System.new(class, 2, "PED_TYPE_EMG", "VOICE_EMG_FBI3")
    end
    const.getEMG_FBI4 = function ()
      return System.new(class, 2, "PED_TYPE_EMG", "VOICE_EMG_FBI4")
    end
    const.getEMG_FBI5 = function ()
      return System.new(class, 2, "PED_TYPE_EMG", "VOICE_EMG_FBI5")
    end
    const.getEMG_FBI6 = function ()
      return System.new(class, 2, "PED_TYPE_EMG", "VOICE_EMG_FBI6")
    end
    const.getEMG_LAPD1 = function ()
      return System.new(class, 2, "PED_TYPE_EMG", "VOICE_EMG_LAPD1")
    end
    const.getEMG_LAPD2 = function ()
      return System.new(class, 2, "PED_TYPE_EMG", "VOICE_EMG_LAPD2")
    end
    const.getEMG_LAPD3 = function ()
      return System.new(class, 2, "PED_TYPE_EMG", "VOICE_EMG_LAPD3")
    end
    const.getEMG_LAPD4 = function ()
      return System.new(class, 2, "PED_TYPE_EMG", "VOICE_EMG_LAPD4")
    end
    const.getEMG_LAPD5 = function ()
      return System.new(class, 2, "PED_TYPE_EMG", "VOICE_EMG_LAPD5")
    end
    const.getEMG_LAPD6 = function ()
      return System.new(class, 2, "PED_TYPE_EMG", "VOICE_EMG_LAPD6")
    end
    const.getEMG_LAPD7 = function ()
      return System.new(class, 2, "PED_TYPE_EMG", "VOICE_EMG_LAPD7")
    end
    const.getEMG_LAPD8 = function ()
      return System.new(class, 2, "PED_TYPE_EMG", "VOICE_EMG_LAPD8")
    end
    const.getEMG_LVPD1 = function ()
      return System.new(class, 2, "PED_TYPE_EMG", "VOICE_EMG_LVPD1")
    end
    const.getEMG_LVPD2 = function ()
      return System.new(class, 2, "PED_TYPE_EMG", "VOICE_EMG_LVPD2")
    end
    const.getEMG_LVPD3 = function ()
      return System.new(class, 2, "PED_TYPE_EMG", "VOICE_EMG_LVPD3")
    end
    const.getEMG_LVPD4 = function ()
      return System.new(class, 2, "PED_TYPE_EMG", "VOICE_EMG_LVPD4")
    end
    const.getEMG_LVPD5 = function ()
      return System.new(class, 2, "PED_TYPE_EMG", "VOICE_EMG_LVPD5")
    end
    const.getEMG_MCOP1 = function ()
      return System.new(class, 2, "PED_TYPE_EMG", "VOICE_EMG_MCOP1")
    end
    const.getEMG_MCOP2 = function ()
      return System.new(class, 2, "PED_TYPE_EMG", "VOICE_EMG_MCOP2")
    end
    const.getEMG_MCOP3 = function ()
      return System.new(class, 2, "PED_TYPE_EMG", "VOICE_EMG_MCOP3")
    end
    const.getEMG_MCOP4 = function ()
      return System.new(class, 2, "PED_TYPE_EMG", "VOICE_EMG_MCOP4")
    end
    const.getEMG_MCOP5 = function ()
      return System.new(class, 2, "PED_TYPE_EMG", "VOICE_EMG_MCOP5")
    end
    const.getEMG_MCOP6 = function ()
      return System.new(class, 2, "PED_TYPE_EMG", "VOICE_EMG_MCOP6")
    end
    const.getEMG_PULASKI = function ()
      return System.new(class, 2, "PED_TYPE_EMG", "VOICE_EMG_PULASKI")
    end
    const.getEMG_RCOP1 = function ()
      return System.new(class, 2, "PED_TYPE_EMG", "VOICE_EMG_RCOP1")
    end
    const.getEMG_RCOP2 = function ()
      return System.new(class, 2, "PED_TYPE_EMG", "VOICE_EMG_RCOP2")
    end
    const.getEMG_RCOP3 = function ()
      return System.new(class, 2, "PED_TYPE_EMG", "VOICE_EMG_RCOP3")
    end
    const.getEMG_RCOP4 = function ()
      return System.new(class, 2, "PED_TYPE_EMG", "VOICE_EMG_RCOP4")
    end
    const.getEMG_SFPD1 = function ()
      return System.new(class, 2, "PED_TYPE_EMG", "VOICE_EMG_SFPD1")
    end
    const.getEMG_SFPD2 = function ()
      return System.new(class, 2, "PED_TYPE_EMG", "VOICE_EMG_SFPD2")
    end
    const.getEMG_SFPD3 = function ()
      return System.new(class, 2, "PED_TYPE_EMG", "VOICE_EMG_SFPD3")
    end
    const.getEMG_SFPD4 = function ()
      return System.new(class, 2, "PED_TYPE_EMG", "VOICE_EMG_SFPD4")
    end
    const.getEMG_SFPD5 = function ()
      return System.new(class, 2, "PED_TYPE_EMG", "VOICE_EMG_SFPD5")
    end
    const.getEMG_SWAT1 = function ()
      return System.new(class, 2, "PED_TYPE_EMG", "VOICE_EMG_SWAT1")
    end
    const.getEMG_SWAT2 = function ()
      return System.new(class, 2, "PED_TYPE_EMG", "VOICE_EMG_SWAT2")
    end
    const.getEMG_SWAT4 = function ()
      return System.new(class, 2, "PED_TYPE_EMG", "VOICE_EMG_SWAT4")
    end
    const.getEMG_SWAT6 = function ()
      return System.new(class, 2, "PED_TYPE_EMG", "VOICE_EMG_SWAT6")
    end
    const.getPLY_AG = function ()
      return System.new(class, 2, "PED_TYPE_PLAYER", "VOICE_PLY_AG")
    end
    const.getPLY_AG2 = function ()
      return System.new(class, 2, "PED_TYPE_PLAYER", "VOICE_PLY_AG2")
    end
    const.getPLY_AR = function ()
      return System.new(class, 2, "PED_TYPE_PLAYER", "VOICE_PLY_AR")
    end
    const.getPLY_AR2 = function ()
      return System.new(class, 2, "PED_TYPE_PLAYER", "VOICE_PLY_AR2")
    end
    const.getPLY_CD = function ()
      return System.new(class, 2, "PED_TYPE_PLAYER", "VOICE_PLY_CD")
    end
    const.getPLY_CD2 = function ()
      return System.new(class, 2, "PED_TYPE_PLAYER", "VOICE_PLY_CD2")
    end
    const.getPLY_CF = function ()
      return System.new(class, 2, "PED_TYPE_PLAYER", "VOICE_PLY_CF")
    end
    const.getPLY_CF2 = function ()
      return System.new(class, 2, "PED_TYPE_PLAYER", "VOICE_PLY_CF2")
    end
    const.getPLY_CG = function ()
      return System.new(class, 2, "PED_TYPE_PLAYER", "VOICE_PLY_CG")
    end
    const.getPLY_CG2 = function ()
      return System.new(class, 2, "PED_TYPE_PLAYER", "VOICE_PLY_CG2")
    end
    const.getPLY_CR = function ()
      return System.new(class, 2, "PED_TYPE_PLAYER", "VOICE_PLY_CR")
    end
    const.getPLY_CR2 = function ()
      return System.new(class, 2, "PED_TYPE_PLAYER", "VOICE_PLY_CR2")
    end
    const.getPLY_PG = function ()
      return System.new(class, 2, "PED_TYPE_PLAYER", "VOICE_PLY_PG")
    end
    const.getPLY_PG2 = function ()
      return System.new(class, 2, "PED_TYPE_PLAYER", "VOICE_PLY_PG2")
    end
    const.getPLY_PR = function ()
      return System.new(class, 2, "PED_TYPE_PLAYER", "VOICE_PLY_PR")
    end
    const.getPLY_PR2 = function ()
      return System.new(class, 2, "PED_TYPE_PLAYER", "VOICE_PLY_PR2")
    end
    const.getPLY_WG = function ()
      return System.new(class, 2, "PED_TYPE_PLAYER", "VOICE_PLY_WG")
    end
    const.getPLY_WG2 = function ()
      return System.new(class, 2, "PED_TYPE_PLAYER", "VOICE_PLY_WG2")
    end
    const.getPLY_WR = function ()
      return System.new(class, 2, "PED_TYPE_PLAYER", "VOICE_PLY_WR")
    end
    const.getPLY_WR2 = function ()
      return System.new(class, 2, "PED_TYPE_PLAYER", "VOICE_PLY_WR2")
    end
    const.getGNG_BALLAS1 = function ()
      return System.new(class, 2, "PED_TYPE_GANG", "VOICE_GNG_BALLAS1")
    end
    const.getGNG_BALLAS2 = function ()
      return System.new(class, 2, "PED_TYPE_GANG", "VOICE_GNG_BALLAS2")
    end
    const.getGNG_BALLAS3 = function ()
      return System.new(class, 2, "PED_TYPE_GANG", "VOICE_GNG_BALLAS3")
    end
    const.getGNG_BALLAS4 = function ()
      return System.new(class, 2, "PED_TYPE_GANG", "VOICE_GNG_BALLAS4")
    end
    const.getGNG_BALLAS5 = function ()
      return System.new(class, 2, "PED_TYPE_GANG", "VOICE_GNG_BALLAS5")
    end
    const.getGNG_BIG_BEAR = function ()
      return System.new(class, 2, "PED_TYPE_GANG", "VOICE_GNG_BIG_BEAR")
    end
    const.getGNG_CESAR = function ()
      return System.new(class, 2, "PED_TYPE_GANG", "VOICE_GNG_CESAR")
    end
    const.getGNG_DNB1 = function ()
      return System.new(class, 2, "PED_TYPE_GANG", "VOICE_GNG_DNB1")
    end
    const.getGNG_DNB2 = function ()
      return System.new(class, 2, "PED_TYPE_GANG", "VOICE_GNG_DNB2")
    end
    const.getGNG_DNB3 = function ()
      return System.new(class, 2, "PED_TYPE_GANG", "VOICE_GNG_DNB3")
    end
    const.getGNG_DNB5 = function ()
      return System.new(class, 2, "PED_TYPE_GANG", "VOICE_GNG_DNB5")
    end
    const.getGNG_DWAINE = function ()
      return System.new(class, 2, "PED_TYPE_GANG", "VOICE_GNG_DWAINE")
    end
    const.getGNG_FAM1 = function ()
      return System.new(class, 2, "PED_TYPE_GANG", "VOICE_GNG_FAM1")
    end
    const.getGNG_FAM2 = function ()
      return System.new(class, 2, "PED_TYPE_GANG", "VOICE_GNG_FAM2")
    end
    const.getGNG_FAM3 = function ()
      return System.new(class, 2, "PED_TYPE_GANG", "VOICE_GNG_FAM3")
    end
    const.getGNG_FAM4 = function ()
      return System.new(class, 2, "PED_TYPE_GANG", "VOICE_GNG_FAM4")
    end
    const.getGNG_FAM5 = function ()
      return System.new(class, 2, "PED_TYPE_GANG", "VOICE_GNG_FAM5")
    end
    const.getGNG_JIZZY = function ()
      return System.new(class, 2, "PED_TYPE_GANG", "VOICE_GNG_JIZZY")
    end
    const.getGNG_LSV1 = function ()
      return System.new(class, 2, "PED_TYPE_GANG", "VOICE_GNG_LSV1")
    end
    const.getGNG_LSV2 = function ()
      return System.new(class, 2, "PED_TYPE_GANG", "VOICE_GNG_LSV2")
    end
    const.getGNG_LSV3 = function ()
      return System.new(class, 2, "PED_TYPE_GANG", "VOICE_GNG_LSV3")
    end
    const.getGNG_LSV4 = function ()
      return System.new(class, 2, "PED_TYPE_GANG", "VOICE_GNG_LSV4")
    end
    const.getGNG_LSV5 = function ()
      return System.new(class, 2, "PED_TYPE_GANG", "VOICE_GNG_LSV5")
    end
    const.getGNG_MACCER = function ()
      return System.new(class, 2, "PED_TYPE_GANG", "VOICE_GNG_MACCER")
    end
    const.getGNG_MAFBOSS = function ()
      return System.new(class, 2, "PED_TYPE_GANG", "VOICE_GNG_MAFBOSS")
    end
    const.getGNG_OGLOC = function ()
      return System.new(class, 2, "PED_TYPE_GANG", "VOICE_GNG_OGLOC")
    end
    const.getGNG_RYDER = function ()
      return System.new(class, 2, "PED_TYPE_GANG", "VOICE_GNG_RYDER")
    end
    const.getGNG_SFR1 = function ()
      return System.new(class, 2, "PED_TYPE_GANG", "VOICE_GNG_SFR1")
    end
    const.getGNG_SFR2 = function ()
      return System.new(class, 2, "PED_TYPE_GANG", "VOICE_GNG_SFR2")
    end
    const.getGNG_SFR3 = function ()
      return System.new(class, 2, "PED_TYPE_GANG", "VOICE_GNG_SFR3")
    end
    const.getGNG_SFR4 = function ()
      return System.new(class, 2, "PED_TYPE_GANG", "VOICE_GNG_SFR4")
    end
    const.getGNG_SFR5 = function ()
      return System.new(class, 2, "PED_TYPE_GANG", "VOICE_GNG_SFR5")
    end
    const.getGNG_SMOKE = function ()
      return System.new(class, 2, "PED_TYPE_GANG", "VOICE_GNG_SMOKE")
    end
    const.getGNG_STRI1 = function ()
      return System.new(class, 2, "PED_TYPE_GANG", "VOICE_GNG_STRI1")
    end
    const.getGNG_STRI2 = function ()
      return System.new(class, 2, "PED_TYPE_GANG", "VOICE_GNG_STRI2")
    end
    const.getGNG_STRI4 = function ()
      return System.new(class, 2, "PED_TYPE_GANG", "VOICE_GNG_STRI4")
    end
    const.getGNG_STRI5 = function ()
      return System.new(class, 2, "PED_TYPE_GANG", "VOICE_GNG_STRI5")
    end
    const.getGNG_SWEET = function ()
      return System.new(class, 2, "PED_TYPE_GANG", "VOICE_GNG_SWEET")
    end
    const.getGNG_TBONE = function ()
      return System.new(class, 2, "PED_TYPE_GANG", "VOICE_GNG_TBONE")
    end
    const.getGNG_TORENO = function ()
      return System.new(class, 2, "PED_TYPE_GANG", "VOICE_GNG_TORENO")
    end
    const.getGNG_TRUTH = function ()
      return System.new(class, 2, "PED_TYPE_GANG", "VOICE_GNG_TRUTH")
    end
    const.getGNG_VLA1 = function ()
      return System.new(class, 2, "PED_TYPE_GANG", "VOICE_GNG_VLA1")
    end
    const.getGNG_VLA2 = function ()
      return System.new(class, 2, "PED_TYPE_GANG", "VOICE_GNG_VLA2")
    end
    const.getGNG_VLA3 = function ()
      return System.new(class, 2, "PED_TYPE_GANG", "VOICE_GNG_VLA3")
    end
    const.getGNG_VLA4 = function ()
      return System.new(class, 2, "PED_TYPE_GANG", "VOICE_GNG_VLA4")
    end
    const.getGNG_VLA5 = function ()
      return System.new(class, 2, "PED_TYPE_GANG", "VOICE_GNG_VLA5")
    end
    const.getGNG_VMAFF1 = function ()
      return System.new(class, 2, "PED_TYPE_GANG", "VOICE_GNG_VMAFF1")
    end
    const.getGNG_VMAFF2 = function ()
      return System.new(class, 2, "PED_TYPE_GANG", "VOICE_GNG_VMAFF2")
    end
    const.getGNG_VMAFF3 = function ()
      return System.new(class, 2, "PED_TYPE_GANG", "VOICE_GNG_VMAFF3")
    end
    const.getGNG_VMAFF4 = function ()
      return System.new(class, 2, "PED_TYPE_GANG", "VOICE_GNG_VMAFF4")
    end
    const.getGNG_VMAFF5 = function ()
      return System.new(class, 2, "PED_TYPE_GANG", "VOICE_GNG_VMAFF5")
    end
    const.getGNG_WOOZIE = function ()
      return System.new(class, 2, "PED_TYPE_GANG", "VOICE_GNG_WOOZIE")
    end
    const.getGFD_BARBARA = function ()
      return System.new(class, 2, "PED_TYPE_GFD", "VOICE_GFD_BARBARA")
    end
    const.getGFD_BMOBAR = function ()
      return System.new(class, 2, "PED_TYPE_GFD", "VOICE_GFD_BMOBAR")
    end
    const.getGFD_BMYBARB = function ()
      return System.new(class, 2, "PED_TYPE_GFD", "VOICE_GFD_BMYBARB")
    end
    const.getGFD_BMYTATT = function ()
      return System.new(class, 2, "PED_TYPE_GFD", "VOICE_GFD_BMYTATT")
    end
    const.getGFD_CATALINA = function ()
      return System.new(class, 2, "PED_TYPE_GFD", "VOICE_GFD_CATALINA")
    end
    const.getGFD_DENISE = function ()
      return System.new(class, 2, "PED_TYPE_GFD", "VOICE_GFD_DENISE")
    end
    const.getGFD_HELENA = function ()
      return System.new(class, 2, "PED_TYPE_GFD", "VOICE_GFD_HELENA")
    end
    const.getGFD_KATIE = function ()
      return System.new(class, 2, "PED_TYPE_GFD", "VOICE_GFD_KATIE")
    end
    const.getGFD_MICHELLE = function ()
      return System.new(class, 2, "PED_TYPE_GFD", "VOICE_GFD_MICHELLE")
    end
    const.getGFD_MILLIE = function ()
      return System.new(class, 2, "PED_TYPE_GFD", "VOICE_GFD_MILLIE")
    end
    const.getGFD_POL_ANN = function ()
      return System.new(class, 2, "PED_TYPE_GFD", "VOICE_GFD_POL_ANN")
    end
    const.getGFD_WFYBURG = function ()
      return System.new(class, 2, "PED_TYPE_GFD", "VOICE_GFD_WFYBURG")
    end
    const.getGFD_WFYCLOT = function ()
      return System.new(class, 2, "PED_TYPE_GFD", "VOICE_GFD_WFYCLOT")
    end
    const.getGFD_WMYAMMO = function ()
      return System.new(class, 2, "PED_TYPE_GFD", "VOICE_GFD_WMYAMMO")
    end
    const.getGFD_WMYBARB = function ()
      return System.new(class, 2, "PED_TYPE_GFD", "VOICE_GFD_WMYBARB")
    end
    const.getGFD_WMYBELL = function ()
      return System.new(class, 2, "PED_TYPE_GFD", "VOICE_GFD_WMYBELL")
    end
    const.getGFD_WMYCLOT = function ()
      return System.new(class, 2, "PED_TYPE_GFD", "VOICE_GFD_WMYCLOT")
    end
    const.getGFD_WMYPIZZ = function ()
      return System.new(class, 2, "PED_TYPE_GFD", "VOICE_GFD_WMYPIZZ")
    end
    class = {
      getDISABLED = getDISABLED,
      getGEN_BBDYG1 = getGEN_BBDYG1,
      getGEN_BBDYG2 = getGEN_BBDYG2,
      getGEN_BFORI = getGEN_BFORI,
      getGEN_BFOST = getGEN_BFOST,
      getGEN_BFYBE = getGEN_BFYBE,
      getGEN_BFYBU = getGEN_BFYBU,
      getGEN_BFYCRP = getGEN_BFYCRP,
      getGEN_BFYPRO = getGEN_BFYPRO,
      getGEN_BFYRI = getGEN_BFYRI,
      getGEN_BFYST = getGEN_BFYST,
      getGEN_BIKDRUG = getGEN_BIKDRUG,
      getGEN_BIKERA = getGEN_BIKERA,
      getGEN_BIKERB = getGEN_BIKERB,
      getGEN_BMOCD = getGEN_BMOCD,
      getGEN_BMORI = getGEN_BMORI,
      getGEN_BMOSEC = getGEN_BMOSEC,
      getGEN_BMOST = getGEN_BMOST,
      getGEN_BMOTR1 = getGEN_BMOTR1,
      getGEN_BMYAP = getGEN_BMYAP,
      getGEN_BMYBE = getGEN_BMYBE,
      getGEN_BMYBOUN = getGEN_BMYBOUN,
      getGEN_BMYBOX = getGEN_BMYBOX,
      getGEN_BMYBU = getGEN_BMYBU,
      getGEN_BMYCG = getGEN_BMYCG,
      getGEN_BMYCON = getGEN_BMYCON,
      getGEN_BMYCR = getGEN_BMYCR,
      getGEN_BMYDJ = getGEN_BMYDJ,
      getGEN_BMYDRUG = getGEN_BMYDRUG,
      getGEN_BMYMOUN = getGEN_BMYMOUN,
      getGEN_BMYPOL1 = getGEN_BMYPOL1,
      getGEN_BMYPOL2 = getGEN_BMYPOL2,
      getGEN_BMYRI = getGEN_BMYRI,
      getGEN_BMYST = getGEN_BMYST,
      getGEN_BYMPI = getGEN_BYMPI,
      getGEN_CWFOFR = getGEN_CWFOFR,
      getGEN_CWFOHB = getGEN_CWFOHB,
      getGEN_CWFYFR1 = getGEN_CWFYFR1,
      getGEN_CWFYFR2 = getGEN_CWFYFR2,
      getGEN_CWFYHB1 = getGEN_CWFYHB1,
      getGEN_CWMOFR1 = getGEN_CWMOFR1,
      getGEN_CWMOHB1 = getGEN_CWMOHB1,
      getGEN_CWMOHB2 = getGEN_CWMOHB2,
      getGEN_CWMYFR = getGEN_CWMYFR,
      getGEN_CWMYHB1 = getGEN_CWMYHB1,
      getGEN_CWMYHB2 = getGEN_CWMYHB2,
      getGEN_DNFOLC1 = getGEN_DNFOLC1,
      getGEN_DNFOLC2 = getGEN_DNFOLC2,
      getGEN_DNFYLC = getGEN_DNFYLC,
      getGEN_DNMOLC1 = getGEN_DNMOLC1,
      getGEN_DNMOLC2 = getGEN_DNMOLC2,
      getGEN_DNMYLC = getGEN_DNMYLC,
      getGEN_DWFOLC = getGEN_DWFOLC,
      getGEN_DWFYLC1 = getGEN_DWFYLC1,
      getGEN_DWFYLC2 = getGEN_DWFYLC2,
      getGEN_DWMOLC1 = getGEN_DWMOLC1,
      getGEN_DWMOLC2 = getGEN_DWMOLC2,
      getGEN_DWMYLC1 = getGEN_DWMYLC1,
      getGEN_DWMYLC2 = getGEN_DWMYLC2,
      getGEN_HFORI = getGEN_HFORI,
      getGEN_HFOST = getGEN_HFOST,
      getGEN_HFYBE = getGEN_HFYBE,
      getGEN_HFYPRO = getGEN_HFYPRO,
      getGEN_HFYRI = getGEN_HFYRI,
      getGEN_HFYST = getGEN_HFYST,
      getGEN_HMORI = getGEN_HMORI,
      getGEN_HMOST = getGEN_HMOST,
      getGEN_HMYBE = getGEN_HMYBE,
      getGEN_HMYCM = getGEN_HMYCM,
      getGEN_HMYCR = getGEN_HMYCR,
      getGEN_HMYDRUG = getGEN_HMYDRUG,
      getGEN_HMYRI = getGEN_HMYRI,
      getGEN_HMYST = getGEN_HMYST,
      getGEN_IMYST = getGEN_IMYST,
      getGEN_IRFYST = getGEN_IRFYST,
      getGEN_IRMYST = getGEN_IRMYST,
      getGEN_MAFFA = getGEN_MAFFA,
      getGEN_MAFFB = getGEN_MAFFB,
      getGEN_MALE01 = getGEN_MALE01,
      getGEN_NOVOICE = getGEN_NOVOICE,
      getGEN_OFORI = getGEN_OFORI,
      getGEN_OFOST = getGEN_OFOST,
      getGEN_OFYRI = getGEN_OFYRI,
      getGEN_OFYST = getGEN_OFYST,
      getGEN_OMOBOAT = getGEN_OMOBOAT,
      getGEN_OMOKUNG = getGEN_OMOKUNG,
      getGEN_OMORI = getGEN_OMORI,
      getGEN_OMOST = getGEN_OMOST,
      getGEN_OMYRI = getGEN_OMYRI,
      getGEN_OMYST = getGEN_OMYST,
      getGEN_SBFORI = getGEN_SBFORI,
      getGEN_SBFOST = getGEN_SBFOST,
      getGEN_SBFYPRO = getGEN_SBFYPRO,
      getGEN_SBFYRI = getGEN_SBFYRI,
      getGEN_SBFYST = getGEN_SBFYST,
      getGEN_SBFYSTR = getGEN_SBFYSTR,
      getGEN_SBMOCD = getGEN_SBMOCD,
      getGEN_SBMORI = getGEN_SBMORI,
      getGEN_SBMOST = getGEN_SBMOST,
      getGEN_SBMOTR1 = getGEN_SBMOTR1,
      getGEN_SBMOTR2 = getGEN_SBMOTR2,
      getGEN_SBMYCR = getGEN_SBMYCR,
      getGEN_SBMYRI = getGEN_SBMYRI,
      getGEN_SBMYST = getGEN_SBMYST,
      getGEN_SBMYTR3 = getGEN_SBMYTR3,
      getGEN_SFYPRO = getGEN_SFYPRO,
      getGEN_SHFYPRO = getGEN_SHFYPRO,
      getGEN_SHMYCR = getGEN_SHMYCR,
      getGEN_SMYST = getGEN_SMYST,
      getGEN_SMYST2 = getGEN_SMYST2,
      getGEN_SOFORI = getGEN_SOFORI,
      getGEN_SOFOST = getGEN_SOFOST,
      getGEN_SOFYBU = getGEN_SOFYBU,
      getGEN_SOFYRI = getGEN_SOFYRI,
      getGEN_SOFYST = getGEN_SOFYST,
      getGEN_SOMOBU = getGEN_SOMOBU,
      getGEN_SOMORI = getGEN_SOMORI,
      getGEN_SOMOST = getGEN_SOMOST,
      getGEN_SOMYAP = getGEN_SOMYAP,
      getGEN_SOMYBU = getGEN_SOMYBU,
      getGEN_SOMYRI = getGEN_SOMYRI,
      getGEN_SOMYST = getGEN_SOMYST,
      getGEN_SWFOPRO = getGEN_SWFOPRO,
      getGEN_SWFORI = getGEN_SWFORI,
      getGEN_SWFOST = getGEN_SWFOST,
      getGEN_SWFYRI = getGEN_SWFYRI,
      getGEN_SWFYST = getGEN_SWFYST,
      getGEN_SWFYSTR = getGEN_SWFYSTR,
      getGEN_SWMOCD = getGEN_SWMOCD,
      getGEN_SWMORI = getGEN_SWMORI,
      getGEN_SWMOST = getGEN_SWMOST,
      getGEN_SWMOTR1 = getGEN_SWMOTR1,
      getGEN_SWMOTR2 = getGEN_SWMOTR2,
      getGEN_SWMOTR3 = getGEN_SWMOTR3,
      getGEN_SWMOTR4 = getGEN_SWMOTR4,
      getGEN_SWMOTR5 = getGEN_SWMOTR5,
      getGEN_SWMYCR = getGEN_SWMYCR,
      getGEN_SWMYHP1 = getGEN_SWMYHP1,
      getGEN_SWMYHP2 = getGEN_SWMYHP2,
      getGEN_SWMYRI = getGEN_SWMYRI,
      getGEN_SWMYST = getGEN_SWMYST,
      getGEN_VBFYPRO = getGEN_VBFYPRO,
      getGEN_VBFYST2 = getGEN_VBFYST2,
      getGEN_VBMOCD = getGEN_VBMOCD,
      getGEN_VBMYCR = getGEN_VBMYCR,
      getGEN_VBMYELV = getGEN_VBMYELV,
      getGEN_VHFYPRO = getGEN_VHFYPRO,
      getGEN_VHFYST3 = getGEN_VHFYST3,
      getGEN_VHMYCR = getGEN_VHMYCR,
      getGEN_VHMYELV = getGEN_VHMYELV,
      getGEN_VIMYELV = getGEN_VIMYELV,
      getGEN_VWFYPRO = getGEN_VWFYPRO,
      getGEN_VWFYST1 = getGEN_VWFYST1,
      getGEN_VWFYWAI = getGEN_VWFYWAI,
      getGEN_VWMOTR1 = getGEN_VWMOTR1,
      getGEN_VWMOTR2 = getGEN_VWMOTR2,
      getGEN_VWMYAP = getGEN_VWMYAP,
      getGEN_VWMYBJD = getGEN_VWMYBJD,
      getGEN_VWMYCD = getGEN_VWMYCD,
      getGEN_VWMYCR = getGEN_VWMYCR,
      getGEN_WFOPJ = getGEN_WFOPJ,
      getGEN_WFORI = getGEN_WFORI,
      getGEN_WFOST = getGEN_WFOST,
      getGEN_WFYBE = getGEN_WFYBE,
      getGEN_WFYBU = getGEN_WFYBU,
      getGEN_WFYCRK = getGEN_WFYCRK,
      getGEN_WFYCRP = getGEN_WFYCRP,
      getGEN_WFYJG = getGEN_WFYJG,
      getGEN_WFYLG = getGEN_WFYLG,
      getGEN_WFYPRO = getGEN_WFYPRO,
      getGEN_WFYRI = getGEN_WFYRI,
      getGEN_WFYRO = getGEN_WFYRO,
      getGEN_WFYST = getGEN_WFYST,
      getGEN_WFYSTEW = getGEN_WFYSTEW,
      getGEN_WMOMIB = getGEN_WMOMIB,
      getGEN_WMOPJ = getGEN_WMOPJ,
      getGEN_WMOPREA = getGEN_WMOPREA,
      getGEN_WMORI = getGEN_WMORI,
      getGEN_WMOSCI = getGEN_WMOSCI,
      getGEN_WMOST = getGEN_WMOST,
      getGEN_WMOTR1 = getGEN_WMOTR1,
      getGEN_WMYBE = getGEN_WMYBE,
      getGEN_WMYBMX = getGEN_WMYBMX,
      getGEN_WMYBOUN = getGEN_WMYBOUN,
      getGEN_WMYBOX = getGEN_WMYBOX,
      getGEN_WMYBP = getGEN_WMYBP,
      getGEN_WMYBU = getGEN_WMYBU,
      getGEN_WMYCD1 = getGEN_WMYCD1,
      getGEN_WMYCD2 = getGEN_WMYCD2,
      getGEN_WMYCH = getGEN_WMYCH,
      getGEN_WMYCON = getGEN_WMYCON,
      getGEN_WMYCONB = getGEN_WMYCONB,
      getGEN_WMYCR = getGEN_WMYCR,
      getGEN_WMYDRUG = getGEN_WMYDRUG,
      getGEN_WMYGAR = const.getGEN_WMYGAR,
      getGEN_WMYGOL1 = const.getGEN_WMYGOL1,
      getGEN_WMYGOL2 = const.getGEN_WMYGOL2,
      getGEN_WMYJG = const.getGEN_WMYJG,
      getGEN_WMYLG = const.getGEN_WMYLG,
      getGEN_WMYMECH = const.getGEN_WMYMECH,
      getGEN_WMYMOUN = const.getGEN_WMYMOUN,
      getGEN_WMYPLT = const.getGEN_WMYPLT,
      getGEN_WMYRI = const.getGEN_WMYRI,
      getGEN_WMYRO = const.getGEN_WMYRO,
      getGEN_WMYSGRD = const.getGEN_WMYSGRD,
      getGEN_WMYSKAT = const.getGEN_WMYSKAT,
      getGEN_WMYST = const.getGEN_WMYST,
      getGEN_WMYTX1 = const.getGEN_WMYTX1,
      getGEN_WMYTX2 = const.getGEN_WMYTX2,
      getGEN_WMYVA = const.getGEN_WMYVA,
      getEMG_ARMY1 = const.getEMG_ARMY1,
      getEMG_ARMY2 = const.getEMG_ARMY2,
      getEMG_ARMY3 = const.getEMG_ARMY3,
      getEMG_EMT1 = const.getEMG_EMT1,
      getEMG_EMT2 = const.getEMG_EMT2,
      getEMG_EMT3 = const.getEMG_EMT3,
      getEMG_EMT4 = const.getEMG_EMT4,
      getEMG_EMT5 = const.getEMG_EMT5,
      getEMG_FBI2 = const.getEMG_FBI2,
      getEMG_FBI3 = const.getEMG_FBI3,
      getEMG_FBI4 = const.getEMG_FBI4,
      getEMG_FBI5 = const.getEMG_FBI5,
      getEMG_FBI6 = const.getEMG_FBI6,
      getEMG_LAPD1 = const.getEMG_LAPD1,
      getEMG_LAPD2 = const.getEMG_LAPD2,
      getEMG_LAPD3 = const.getEMG_LAPD3,
      getEMG_LAPD4 = const.getEMG_LAPD4,
      getEMG_LAPD5 = const.getEMG_LAPD5,
      getEMG_LAPD6 = const.getEMG_LAPD6,
      getEMG_LAPD7 = const.getEMG_LAPD7,
      getEMG_LAPD8 = const.getEMG_LAPD8,
      getEMG_LVPD1 = const.getEMG_LVPD1,
      getEMG_LVPD2 = const.getEMG_LVPD2,
      getEMG_LVPD3 = const.getEMG_LVPD3,
      getEMG_LVPD4 = const.getEMG_LVPD4,
      getEMG_LVPD5 = const.getEMG_LVPD5,
      getEMG_MCOP1 = const.getEMG_MCOP1,
      getEMG_MCOP2 = const.getEMG_MCOP2,
      getEMG_MCOP3 = const.getEMG_MCOP3,
      getEMG_MCOP4 = const.getEMG_MCOP4,
      getEMG_MCOP5 = const.getEMG_MCOP5,
      getEMG_MCOP6 = const.getEMG_MCOP6,
      getEMG_PULASKI = const.getEMG_PULASKI,
      getEMG_RCOP1 = const.getEMG_RCOP1,
      getEMG_RCOP2 = const.getEMG_RCOP2,
      getEMG_RCOP3 = const.getEMG_RCOP3,
      getEMG_RCOP4 = const.getEMG_RCOP4,
      getEMG_SFPD1 = const.getEMG_SFPD1,
      getEMG_SFPD2 = const.getEMG_SFPD2,
      getEMG_SFPD3 = const.getEMG_SFPD3,
      getEMG_SFPD4 = const.getEMG_SFPD4,
      getEMG_SFPD5 = const.getEMG_SFPD5,
      getEMG_SWAT1 = const.getEMG_SWAT1,
      getEMG_SWAT2 = const.getEMG_SWAT2,
      getEMG_SWAT4 = const.getEMG_SWAT4,
      getEMG_SWAT6 = const.getEMG_SWAT6,
      getPLY_AG = const.getPLY_AG,
      getPLY_AG2 = const.getPLY_AG2,
      getPLY_AR = const.getPLY_AR,
      getPLY_AR2 = const.getPLY_AR2,
      getPLY_CD = const.getPLY_CD,
      getPLY_CD2 = const.getPLY_CD2,
      getPLY_CF = const.getPLY_CF,
      getPLY_CF2 = const.getPLY_CF2,
      getPLY_CG = const.getPLY_CG,
      getPLY_CG2 = const.getPLY_CG2,
      getPLY_CR = const.getPLY_CR,
      getPLY_CR2 = const.getPLY_CR2,
      getPLY_PG = const.getPLY_PG,
      getPLY_PG2 = const.getPLY_PG2,
      getPLY_PR = const.getPLY_PR,
      getPLY_PR2 = const.getPLY_PR2,
      getPLY_WG = const.getPLY_WG,
      getPLY_WG2 = const.getPLY_WG2,
      getPLY_WR = const.getPLY_WR,
      getPLY_WR2 = const.getPLY_WR2,
      getGNG_BALLAS1 = const.getGNG_BALLAS1,
      getGNG_BALLAS2 = const.getGNG_BALLAS2,
      getGNG_BALLAS3 = const.getGNG_BALLAS3,
      getGNG_BALLAS4 = const.getGNG_BALLAS4,
      getGNG_BALLAS5 = const.getGNG_BALLAS5,
      getGNG_BIG_BEAR = const.getGNG_BIG_BEAR,
      getGNG_CESAR = const.getGNG_CESAR,
      getGNG_DNB1 = const.getGNG_DNB1,
      getGNG_DNB2 = const.getGNG_DNB2,
      getGNG_DNB3 = const.getGNG_DNB3,
      getGNG_DNB5 = const.getGNG_DNB5,
      getGNG_DWAINE = const.getGNG_DWAINE,
      getGNG_FAM1 = const.getGNG_FAM1,
      getGNG_FAM2 = const.getGNG_FAM2,
      getGNG_FAM3 = const.getGNG_FAM3,
      getGNG_FAM4 = const.getGNG_FAM4,
      getGNG_FAM5 = const.getGNG_FAM5,
      getGNG_JIZZY = const.getGNG_JIZZY,
      getGNG_LSV1 = const.getGNG_LSV1,
      getGNG_LSV2 = const.getGNG_LSV2,
      getGNG_LSV3 = const.getGNG_LSV3,
      getGNG_LSV4 = const.getGNG_LSV4,
      getGNG_LSV5 = const.getGNG_LSV5,
      getGNG_MACCER = const.getGNG_MACCER,
      getGNG_MAFBOSS = const.getGNG_MAFBOSS,
      getGNG_OGLOC = const.getGNG_OGLOC,
      getGNG_RYDER = const.getGNG_RYDER,
      getGNG_SFR1 = const.getGNG_SFR1,
      getGNG_SFR2 = const.getGNG_SFR2,
      getGNG_SFR3 = const.getGNG_SFR3,
      getGNG_SFR4 = const.getGNG_SFR4,
      getGNG_SFR5 = const.getGNG_SFR5,
      getGNG_SMOKE = const.getGNG_SMOKE,
      getGNG_STRI1 = const.getGNG_STRI1,
      getGNG_STRI2 = const.getGNG_STRI2,
      getGNG_STRI4 = const.getGNG_STRI4,
      getGNG_STRI5 = const.getGNG_STRI5,
      getGNG_SWEET = const.getGNG_SWEET,
      getGNG_TBONE = const.getGNG_TBONE,
      getGNG_TORENO = const.getGNG_TORENO,
      getGNG_TRUTH = const.getGNG_TRUTH,
      getGNG_VLA1 = const.getGNG_VLA1,
      getGNG_VLA2 = const.getGNG_VLA2,
      getGNG_VLA3 = const.getGNG_VLA3,
      getGNG_VLA4 = const.getGNG_VLA4,
      getGNG_VLA5 = const.getGNG_VLA5,
      getGNG_VMAFF1 = const.getGNG_VMAFF1,
      getGNG_VMAFF2 = const.getGNG_VMAFF2,
      getGNG_VMAFF3 = const.getGNG_VMAFF3,
      getGNG_VMAFF4 = const.getGNG_VMAFF4,
      getGNG_VMAFF5 = const.getGNG_VMAFF5,
      getGNG_WOOZIE = const.getGNG_WOOZIE,
      getGFD_BARBARA = const.getGFD_BARBARA,
      getGFD_BMOBAR = const.getGFD_BMOBAR,
      getGFD_BMYBARB = const.getGFD_BMYBARB,
      getGFD_BMYTATT = const.getGFD_BMYTATT,
      getGFD_CATALINA = const.getGFD_CATALINA,
      getGFD_DENISE = const.getGFD_DENISE,
      getGFD_HELENA = const.getGFD_HELENA,
      getGFD_KATIE = const.getGFD_KATIE,
      getGFD_MICHELLE = const.getGFD_MICHELLE,
      getGFD_MILLIE = const.getGFD_MILLIE,
      getGFD_POL_ANN = const.getGFD_POL_ANN,
      getGFD_WFYBURG = const.getGFD_WFYBURG,
      getGFD_WFYCLOT = const.getGFD_WFYCLOT,
      getGFD_WMYAMMO = const.getGFD_WMYAMMO,
      getGFD_WMYBARB = const.getGFD_WMYBARB,
      getGFD_WMYBELL = const.getGFD_WMYBELL,
      getGFD_WMYCLOT = const.getGFD_WMYCLOT,
      getGFD_WMYPIZZ = const.getGFD_WMYPIZZ,
      __ctor__ = {
        __ctor1__,
        __ctor2__
      }
    }
    return class
  end)
end)
