-- Generated by CSharp.lua Compiler
local System = System
local SlipeServerGame
local SlipeServerIO
local SlipeSharedElements
System.import(function (out)
  SlipeServerGame = Slipe.Server.Game
  SlipeServerIO = Slipe.Server.IO
  SlipeSharedElements = Slipe.Shared.Elements
end)
System.namespace("Slipe.Server.Elements", function (namespace)
  namespace.class("RootElement", function (namespace)
    local HandleEvent, class, __ctor__
    __ctor__ = function (this, element)
      SlipeSharedElements.Element.__ctor__[2](this, element)
      class.OnAccountDataChange = class.OnAccountDataChange + function (account, key, value)
        account:HandleDataChange(key, value)
      end
      class.OnBanAdded = class.OnBanAdded + function (ban)
        ban:HandleAdded()
      end
      class.OnBanRemoved = class.OnBanRemoved + function (ban, responsiblePlayer)
        ban:HandleRemoved(responsiblePlayer)
      end
      class.OnPlayerConnect = class.OnPlayerConnect + function (nickName, Ip, username, serial, versionNumber, versionString)
        SlipeServerGame.GameServer.HandlePlayerConnected(nickName, Ip, username, serial, versionNumber, versionString)
      end
      class.OnChatMessage = class.OnChatMessage + function (message, playerOrResource)
        SlipeServerIO.ChatBox.HandleMessage(message, playerOrResource)
      end
      class.OnDebugMessage = class.OnDebugMessage + function (message, level, file, line, color)
        SlipeServerGame.GameServer.getDebug():HandleMessage(message, level, file, line, color)
      end
      class.OnSettingChange = class.OnSettingChange + function (setting, oldValue, newValue)
        SlipeServerGame.GameServer.HandleSettingChange(setting, oldValue, newValue)
      end
    end
    HandleEvent = function (this, eventName, element, p1, p2, p3, p4, p5, p6, p7, p8)
      local default = class.OnMiscelaniousEvent
      if default ~= nil then
        default(eventName, element, p1, p2, p3, p4, p5, p6, p7, p8)
      end
    end
    class = {
      __inherits__ = function (out)
        return {
          out.Slipe.Shared.Elements.Element
        }
      end,
      HandleEvent = HandleEvent,
      __ctor__ = __ctor__,
      __metadata__ = function (out)
        return {
          class = { 0x6, System.new(out.Slipe.Shared.Elements.DefaultElementClassAttribute, 2, 36 --[[ElementType.Root]]) }
        }
      end
    }
    return class
  end)
end)
