-- Generated by CSharp.lua Compiler
local System = System
local SlipeMtaDefinitions
System.import(function (out)
  SlipeMtaDefinitions = Slipe.MtaDefinitions
end)
System.namespace("Slipe.Server.Events", function (namespace)
  -- <summary>
  -- Class that wraps event utility methods
  -- </summary>
  namespace.class("Event", function (namespace)
    local Cancel, getWasCancelled
    -- <summary>
    -- Cancel the current event
    -- </summary>
    Cancel = function (reason, cancel)
      SlipeMtaDefinitions.MtaServer.CancelEvent(cancel, reason)
    end
    getWasCancelled = function ()
      return SlipeMtaDefinitions.MtaShared.WasEventCancelled()
    end
    return {
      Cancel = Cancel,
      getWasCancelled = getWasCancelled
    }
  end)
end)
