-- Generated by CSharp.lua Compiler
local System = System
local SlipeMtaDefinitions
System.import(function (out)
  SlipeMtaDefinitions = Slipe.MtaDefinitions
end)
System.namespace("Slipe.Client.Effects", function (namespace)
  -- <summary>
  -- Class that enables creation of short lived effects in the world
  -- </summary>
  namespace.class("Fx", function (namespace)
    local Blood, BulletImpact, BulletSplash, Debris, FootSplash, Glass, Gunshot, PunchImpact, 
    Sparks, Sparks1, TankFire, TyreBurst, WaterHydrant, WaterSplash, Wood
    -- <summary>
    -- Creates a blood splatter particle effect.
    -- </summary>
    Blood = function (position, direction, count, brightness)
      return SlipeMtaDefinitions.MtaClient.FxAddBlood(position.X, position.Y, position.Z, direction.X, direction.Y, direction.Z, count, brightness)
    end
    -- <summary>
    -- Creates a bullet impact particle effect, consisting of a small smoke cloud and a number of sparks.
    -- </summary>
    BulletImpact = function (position, direction, smokeSize, sparkCount, smokeIntensity)
      return SlipeMtaDefinitions.MtaClient.FxAddBulletImpact(position.X, position.Y, position.Z, direction.X, direction.Y, direction.Z, smokeSize, sparkCount, smokeIntensity)
    end
    -- <summary>
    -- This function creates a bullet splash particle effect, normally created when shooting into water.
    -- </summary>
    BulletSplash = function (position)
      return SlipeMtaDefinitions.MtaClient.FxAddBulletSplash(position.X, position.Y, position.Z)
    end
    -- <summary>
    -- Creates a debris particle effect (e.g. bits that fly off a car when ramming a wall).
    -- </summary>
    Debris = function (position, color, scale, count)
      return SlipeMtaDefinitions.MtaClient.FxAddDebris(position.X, position.Y, position.Z, color:getR(), color:getG(), color:getB(), color:getA(), scale, count)
    end
    -- <summary>
    -- This function creates a foot splash particle effect, normally created when walking into water.
    -- </summary>
    FootSplash = function (position)
      return SlipeMtaDefinitions.MtaClient.FxAddFootSplash(position.X, position.Y, position.Z)
    end
    -- <summary>
    -- This function creates a glass particle effect.
    -- </summary>
    Glass = function (position, color, scale, count)
      return SlipeMtaDefinitions.MtaClient.FxAddGlass(position.X, position.Y, position.Z, color:getR(), color:getG(), color:getB(), color:getA(), scale, count)
    end
    -- <summary>
    -- This function creates a gunshot particle effect.
    -- </summary>
    Gunshot = function (position, direction, includeSparks)
      return SlipeMtaDefinitions.MtaClient.FxAddGunshot(position.X, position.Y, position.Z, direction.X, direction.Y, direction.Z, includeSparks)
    end
    -- <summary>
    -- Creates a punch impact particle effect (a small dust cloud).
    -- </summary>
    PunchImpact = function (position, direction)
      return SlipeMtaDefinitions.MtaClient.FxAddPunchImpact(position.X, position.Y, position.Z, direction.X, direction.Y, direction.Z)
    end
    -- <summary>
    -- Creates a number of sparks originating from a point
    -- </summary>
    Sparks = function (position, direction, force, count, blur, spread, life)
      return SlipeMtaDefinitions.MtaClient.FxAddSparks(position.X, position.Y, position.Z, direction.X, direction.Y, direction.Z, force, count, 0, 0, 0, blur, spread, life)
    end
    -- <summary>
    -- Creates a number of sparks on a line
    -- </summary>
    Sparks1 = function (lineStart, lineEnd, direction, force, count, blur, spread, life)
      return SlipeMtaDefinitions.MtaClient.FxAddSparks(lineStart.X, lineStart.Y, lineStart.Z, direction.X, direction.Y, direction.Z, force, count, lineEnd.X, lineEnd.Y, lineEnd.Z, blur, spread, life)
    end
    -- <summary>
    -- This function creates a tank firing particle effect.
    -- </summary>
    TankFire = function (position, direction)
      return SlipeMtaDefinitions.MtaClient.FxAddTankFire(position.X, position.Y, position.Z, direction.X, direction.Y, direction.Z)
    end
    -- <summary>
    -- Creates a tyre burst particle effect (a small white smoke puff).
    -- </summary>
    TyreBurst = function (position, direction)
      return SlipeMtaDefinitions.MtaClient.FxAddTyreBurst(position.X, position.Y, position.Z, direction.X, direction.Y, direction.Z)
    end
    -- <summary>
    -- This function creates a water hydrant particle effect.
    -- </summary>
    WaterHydrant = function (position)
      return SlipeMtaDefinitions.MtaClient.FxAddWaterHydrant(position.X, position.Y, position.Z)
    end
    -- <summary>
    -- This function creates a water splash particle effect.
    -- </summary>
    WaterSplash = function (position)
      return SlipeMtaDefinitions.MtaClient.FxAddWaterSplash(position.X, position.Y, position.Z)
    end
    -- <summary>
    -- Creates a wood splinter particle effect.
    -- </summary>
    Wood = function (position, direction, count, brightness)
      return SlipeMtaDefinitions.MtaClient.FxAddWood(position.X, position.Y, position.Z, direction.X, direction.Y, direction.Z, count, brightness)
    end
    return {
      Blood = Blood,
      BulletImpact = BulletImpact,
      BulletSplash = BulletSplash,
      Debris = Debris,
      FootSplash = FootSplash,
      Glass = Glass,
      Gunshot = Gunshot,
      PunchImpact = PunchImpact,
      Sparks = Sparks,
      Sparks1 = Sparks1,
      TankFire = TankFire,
      TyreBurst = TyreBurst,
      WaterHydrant = WaterHydrant,
      WaterSplash = WaterSplash,
      Wood = Wood
    }
  end)
end)
