-- Generated by CSharp.lua Compiler
local System = System
local SlipeMtaDefinitions
local SlipeSharedElements
local SlipeSharedWeapons
System.import(function (out)
  SlipeMtaDefinitions = Slipe.MtaDefinitions
  SlipeSharedElements = Slipe.Shared.Elements
  SlipeSharedWeapons = Slipe.Shared.Weapons
end)
System.namespace("Slipe.Shared.Pickups", function (namespace)
  -- <summary>
  -- Class representing a pickup element
  -- </summary>
  namespace.class("SharedPickup", function (namespace)
    local getPickupType, getAmmo, getWeaponModel, getAmount, Morph, Morph1, Morph2, Morph3, 
    __ctor__
    __ctor__ = function (this, element)
      SlipeSharedElements.PhysicalElement.__ctor__(this, element)
    end
    getPickupType = function (this)
      return SlipeMtaDefinitions.MtaShared.GetPickupType(this.element)
    end
    getAmmo = function (this)
      return SlipeMtaDefinitions.MtaShared.GetPickupAmmo(this.element)
    end
    getWeaponModel = function (this)
      return SlipeSharedWeapons.SharedWeaponModel(SlipeMtaDefinitions.MtaShared.GetPickupWeapon(this.element))
    end
    getAmount = function (this)
      return SlipeMtaDefinitions.MtaShared.GetPickupAmount(this.element)
    end
    -- <summary>
    -- Morphs the pickup into a pickup of a different type
    -- </summary>
    Morph = function (this, type, amount, ammo)
      return SlipeMtaDefinitions.MtaShared.SetPickupType(this.element, type, amount, ammo)
    end
    -- <summary>
    -- Morphs the pickup into a weapon pickup
    -- </summary>
    Morph1 = function (this, weapon, ammo)
      return Morph(this, 2 --[[PickupType.Weapon]], weapon.ID, ammo)
    end
    -- <summary>
    -- Morphs the pickup into a GTA custom pickup
    -- </summary>
    Morph2 = function (this, model)
      return Morph(this, 3 --[[PickupType.Custom]], model, 50)
    end
    -- <summary>
    -- Morphs the pickup into a model pickup taking any model ID
    -- </summary>
    Morph3 = function (this, model)
      return Morph(this, 3 --[[PickupType.Custom]], model, 50)
    end
    return {
      __inherits__ = function (out)
        return {
          out.Slipe.Shared.Elements.PhysicalElement
        }
      end,
      getPickupType = getPickupType,
      getAmmo = getAmmo,
      getWeaponModel = getWeaponModel,
      getAmount = getAmount,
      Morph = Morph,
      Morph1 = Morph1,
      Morph2 = Morph2,
      Morph3 = Morph3,
      __ctor__ = __ctor__
    }
  end)
end)
