-- Generated by CSharp.lua Compiler
local System = System
local SlipeMtaDefinitions
local SlipeSharedVehicles
local SystemNumerics
System.import(function (out)
  SlipeMtaDefinitions = Slipe.MtaDefinitions
  SlipeSharedVehicles = Slipe.Shared.Vehicles
  SystemNumerics = System.Numerics
end)
System.namespace("Slipe.Client.Vehicles", function (namespace)
  namespace.class("BaseVehicleModel", function (namespace)
    local getExhaustPosition, setExhaustPosition, __ctor__
    __ctor__ = function (this, id)
      SlipeSharedVehicles.SharedVehicleModel.__ctor__(this, id)
    end
    getExhaustPosition = function (this)
      local r = SlipeMtaDefinitions.MtaClient.GetVehicleModelExhaustFumesPosition(this.id)
      return SystemNumerics.Vector3(r[1], r[2], r[3])
    end
    setExhaustPosition = function (this, value)
      SlipeMtaDefinitions.MtaClient.SetVehicleModelExhaustFumesPosition(this.id, value.X, value.Y, value.Z)
    end
    return {
      __inherits__ = function (out)
        return {
          out.Slipe.Shared.Vehicles.SharedVehicleModel
        }
      end,
      getExhaustPosition = getExhaustPosition,
      setExhaustPosition = setExhaustPosition,
      __ctor__ = __ctor__
    }
  end)
end)
