-- Generated by CSharp.lua Compiler
local System = System
local SlipeClientVehicles
local SlipeMtaDefinitions
System.import(function (out)
  SlipeClientVehicles = Slipe.Client.Vehicles
  SlipeMtaDefinitions = Slipe.MtaDefinitions
end)
System.namespace("Slipe.Client.Vehicles", function (namespace)
  -- <summary>
  -- Represents a taxi vehicle
  -- </summary>
  namespace.class("Taxi", function (namespace)
    local getTaxiLightOn, setTaxiLightOn, __ctor1__, __ctor2__, __ctor3__
    -- <summary>
    -- Create a vehicle from a model at a position
    -- </summary>
    __ctor1__ = function (this, model, position)
      SlipeClientVehicles.Vehicle.__ctor__[2](this, model, position:__clone__())
    end
    -- <summary>
    -- Create a vehicle model using all createVehicle arguments
    -- </summary>
    __ctor2__ = function (this, model, position, rotation, numberplate, variant1, variant2)
      SlipeClientVehicles.Vehicle.__ctor__[3](this, model, position:__clone__(), rotation:__clone__(), numberplate, variant1, variant2)
    end
    __ctor3__ = function (this, element)
      SlipeClientVehicles.Vehicle.__ctor__[1](this, element)
    end
    getTaxiLightOn = function (this)
      return SlipeMtaDefinitions.MtaShared.IsVehicleTaxiLightOn(this.element)
    end
    setTaxiLightOn = function (this, value)
      SlipeMtaDefinitions.MtaShared.SetVehicleTaxiLightOn(this.element, value)
    end
    return {
      __inherits__ = function (out)
        return {
          out.Slipe.Client.Vehicles.Vehicle
        }
      end,
      getTaxiLightOn = getTaxiLightOn,
      setTaxiLightOn = setTaxiLightOn,
      __ctor__ = {
        __ctor1__,
        __ctor2__,
        __ctor3__
      }
    }
  end)

  -- <summary>
  -- Represents a Taxi model
  -- </summary>
  namespace.class("TaxiModel", function (namespace)
    local getCabbie, getTaxi, class, __ctor__
    __ctor__ = function (this, id)
      SlipeClientVehicles.BaseVehicleModel.__ctor__(this, id)
    end
    getCabbie = function ()
      return class(438)
    end
    getTaxi = function ()
      return class(420)
    end
    class = {
      __inherits__ = function (out)
        return {
          out.Slipe.Client.Vehicles.BaseVehicleModel
        }
      end,
      getCabbie = getCabbie,
      getTaxi = getTaxi,
      __ctor__ = __ctor__
    }
    return class
  end)
end)
