-- Generated by CSharp.lua Compiler
local System = System
local SlipeClientVehicles
System.import(function (out)
  SlipeClientVehicles = Slipe.Client.Vehicles
end)
System.namespace("Slipe.Client.Vehicles", function (namespace)
  -- <summary>
  -- Represents a vehicle model for other road vehicles
  -- </summary>
  namespace.class("VehicleModel", function (namespace)
    local getBf400, getFaggio, getFcr900, getFreeway, getHpv1000, getNrg500, getPcj600, getPizzaboy, 
    getSanchez, getWayfarer, getQuadbike, getBike, getBmx, getMountainbike, getAlpha, getBanshee, 
    getBuffalo, getBullet, getCheetah, getComet, getElegy, getEuros, getFlash, getInfernus, 
    getJester, getPhoenix, getSultan, getSupergt, getTurismo, getUranus, getWindsor, getZr350, 
    getBlade, getBroadway, getBuccaneer, getEsperanto, getRemington, getSavanna, getSlamvan, getTornado, 
    getVoodoo, getBlistacompact, getBravura, getCadrona, getClover, getFeltzer, getFortune, getHermes, 
    getHustler, getMajestic, getManana, getPrevion, getSabre, getStallion, getTampa, getVirgo, 
    getAdmiral, getElegant, getEmperor, getGlendale, getGreenwood, getIntruder, getMerit, getNebula, 
    getOceanic, getPremier, getPrimo, getSentinel, getStafford, getStretch, getSunrise, getTahoma, 
    getVincent, getWashington, getWillard, getAmbulance, getBarracks, getEnforcer, getFbirancher, getFbitruck, 
    getFiretruckladder, getPolicecarls, getPolicecarlv, getPolicecarsf, getPoliceranger, getCementtruck, getDft30, getDozer, 
    getDumper, getDune, getFlatbed, getForklift, getLinerunner, getPacker, getRoadtrain, getSweeper, 
    getTanker, getTowtruck, getTrashmaster, getUtilityvan, getBenson, getBlackboxville, getBobcat, getBoxville, 
    getMule, getPicador, getSadler, getSecuricar, getWalton, getYankee, getYosemite, getBerkleysrcvan, 
    getBurrito, getCamper, getJourney, getMoonbeam, getNewsvan, getPony, getRumpo, getBaggage, 
    getBandito, getBfinjection, getBloodringbanger, getBus, getCaddy, getCoach, getCombineharvester, getHotdog, 
    getHotknife, getHotringracer1, getHotringracer2, getHotringracer3, getMonster1, getMonster2, getMonster3, getMower, 
    getMrwhoopee, getKart, getTractor, getTug, getVortex, getRcBandit, getRcFlowerpot, getRcTiger, 
    getClub, getHuntley, getLandstalker, getMesa, getPatriot, getPerennial, getRancher, getRegina, 
    getRomero, getSandking, getSolair, getStratum, class, __ctor__
    __ctor__ = function (this, id)
      SlipeClientVehicles.BaseVehicleModel.__ctor__(this, id)
    end
    getBf400 = function ()
      return class(581)
    end
    getFaggio = function ()
      return class(462)
    end
    getFcr900 = function ()
      return class(521)
    end
    getFreeway = function ()
      return class(463)
    end
    getHpv1000 = function ()
      return class(523)
    end
    getNrg500 = function ()
      return class(522)
    end
    getPcj600 = function ()
      return class(461)
    end
    getPizzaboy = function ()
      return class(448)
    end
    getSanchez = function ()
      return class(468)
    end
    getWayfarer = function ()
      return class(586)
    end
    getQuadbike = function ()
      return class(471)
    end
    getBike = function ()
      return class(509)
    end
    getBmx = function ()
      return class(481)
    end
    getMountainbike = function ()
      return class(510)
    end
    getAlpha = function ()
      return class(602)
    end
    getBanshee = function ()
      return class(429)
    end
    getBuffalo = function ()
      return class(402)
    end
    getBullet = function ()
      return class(541)
    end
    getCheetah = function ()
      return class(415)
    end
    getComet = function ()
      return class(480)
    end
    getElegy = function ()
      return class(562)
    end
    getEuros = function ()
      return class(587)
    end
    getFlash = function ()
      return class(565)
    end
    getInfernus = function ()
      return class(411)
    end
    getJester = function ()
      return class(559)
    end
    getPhoenix = function ()
      return class(603)
    end
    getSultan = function ()
      return class(560)
    end
    getSupergt = function ()
      return class(506)
    end
    getTurismo = function ()
      return class(451)
    end
    getUranus = function ()
      return class(558)
    end
    getWindsor = function ()
      return class(555)
    end
    getZr350 = function ()
      return class(477)
    end
    getBlade = function ()
      return class(536)
    end
    getBroadway = function ()
      return class(575)
    end
    getBuccaneer = function ()
      return class(518)
    end
    getEsperanto = function ()
      return class(419)
    end
    getRemington = function ()
      return class(534)
    end
    getSavanna = function ()
      return class(567)
    end
    getSlamvan = function ()
      return class(535)
    end
    getTornado = function ()
      return class(576)
    end
    getVoodoo = function ()
      return class(412)
    end
    getBlistacompact = function ()
      return class(496)
    end
    getBravura = function ()
      return class(401)
    end
    getCadrona = function ()
      return class(527)
    end
    getClover = function ()
      return class(542)
    end
    getFeltzer = function ()
      return class(533)
    end
    getFortune = function ()
      return class(526)
    end
    getHermes = function ()
      return class(474)
    end
    getHustler = function ()
      return class(545)
    end
    getMajestic = function ()
      return class(517)
    end
    getManana = function ()
      return class(410)
    end
    getPrevion = function ()
      return class(436)
    end
    getSabre = function ()
      return class(475)
    end
    getStallion = function ()
      return class(439)
    end
    getTampa = function ()
      return class(549)
    end
    getVirgo = function ()
      return class(491)
    end
    getAdmiral = function ()
      return class(445)
    end
    getElegant = function ()
      return class(507)
    end
    getEmperor = function ()
      return class(585)
    end
    getGlendale = function ()
      return class(466)
    end
    getGreenwood = function ()
      return class(492)
    end
    getIntruder = function ()
      return class(546)
    end
    getMerit = function ()
      return class(551)
    end
    getNebula = function ()
      return class(516)
    end
    getOceanic = function ()
      return class(467)
    end
    getPremier = function ()
      return class(426)
    end
    getPrimo = function ()
      return class(547)
    end
    getSentinel = function ()
      return class(405)
    end
    getStafford = function ()
      return class(580)
    end
    getStretch = function ()
      return class(409)
    end
    getSunrise = function ()
      return class(550)
    end
    getTahoma = function ()
      return class(566)
    end
    getVincent = function ()
      return class(540)
    end
    getWashington = function ()
      return class(421)
    end
    getWillard = function ()
      return class(529)
    end
    getAmbulance = function ()
      return class(416)
    end
    getBarracks = function ()
      return class(433)
    end
    getEnforcer = function ()
      return class(427)
    end
    getFbirancher = function ()
      return class(490)
    end
    getFbitruck = function ()
      return class(528)
    end
    getFiretruckladder = function ()
      return class(544)
    end
    getPolicecarls = function ()
      return class(596)
    end
    getPolicecarlv = function ()
      return class(598)
    end
    getPolicecarsf = function ()
      return class(597)
    end
    getPoliceranger = function ()
      return class(599)
    end
    getCementtruck = function ()
      return class(524)
    end
    getDft30 = function ()
      return class(578)
    end
    getDozer = function ()
      return class(486)
    end
    getDumper = function ()
      return class(406)
    end
    getDune = function ()
      return class(573)
    end
    getFlatbed = function ()
      return class(455)
    end
    getForklift = function ()
      return class(530)
    end
    getLinerunner = function ()
      return class(403)
    end
    getPacker = function ()
      return class(443)
    end
    getRoadtrain = function ()
      return class(515)
    end
    getSweeper = function ()
      return class(574)
    end
    getTanker = function ()
      return class(514)
    end
    getTowtruck = function ()
      return class(525)
    end
    getTrashmaster = function ()
      return class(408)
    end
    getUtilityvan = function ()
      return class(552)
    end
    getBenson = function ()
      return class(499)
    end
    getBlackboxville = function ()
      return class(609)
    end
    getBobcat = function ()
      return class(422)
    end
    getBoxville = function ()
      return class(498)
    end
    getMule = function ()
      return class(414)
    end
    getPicador = function ()
      return class(600)
    end
    getSadler = function ()
      return class(543)
    end
    getSecuricar = function ()
      return class(428)
    end
    getWalton = function ()
      return class(478)
    end
    getYankee = function ()
      return class(456)
    end
    getYosemite = function ()
      return class(554)
    end
    getBerkleysrcvan = function ()
      return class(459)
    end
    getBurrito = function ()
      return class(482)
    end
    getCamper = function ()
      return class(483)
    end
    getJourney = function ()
      return class(508)
    end
    getMoonbeam = function ()
      return class(418)
    end
    getNewsvan = function ()
      return class(582)
    end
    getPony = function ()
      return class(413)
    end
    getRumpo = function ()
      return class(440)
    end
    getBaggage = function ()
      return class(485)
    end
    getBandito = function ()
      return class(568)
    end
    getBfinjection = function ()
      return class(424)
    end
    getBloodringbanger = function ()
      return class(504)
    end
    getBus = function ()
      return class(431)
    end
    getCaddy = function ()
      return class(457)
    end
    getCoach = function ()
      return class(437)
    end
    getCombineharvester = function ()
      return class(532)
    end
    getHotdog = function ()
      return class(588)
    end
    getHotknife = function ()
      return class(434)
    end
    getHotringracer1 = function ()
      return class(494)
    end
    getHotringracer2 = function ()
      return class(502)
    end
    getHotringracer3 = function ()
      return class(503)
    end
    getMonster1 = function ()
      return class(444)
    end
    getMonster2 = function ()
      return class(556)
    end
    getMonster3 = function ()
      return class(557)
    end
    getMower = function ()
      return class(572)
    end
    getMrwhoopee = function ()
      return class(423)
    end
    getKart = function ()
      return class(571)
    end
    getTractor = function ()
      return class(531)
    end
    getTug = function ()
      return class(583)
    end
    getVortex = function ()
      return class(539)
    end
    getRcBandit = function ()
      return class(441)
    end
    getRcFlowerpot = function ()
      return class(594)
    end
    getRcTiger = function ()
      return class(564)
    end
    getClub = function ()
      return class(589)
    end
    getHuntley = function ()
      return class(579)
    end
    getLandstalker = function ()
      return class(400)
    end
    getMesa = function ()
      return class(500)
    end
    getPatriot = function ()
      return class(470)
    end
    getPerennial = function ()
      return class(404)
    end
    getRancher = function ()
      return class(489)
    end
    getRegina = function ()
      return class(479)
    end
    getRomero = function ()
      return class(442)
    end
    getSandking = function ()
      return class(495)
    end
    getSolair = function ()
      return class(458)
    end
    getStratum = function ()
      return class(561)
    end
    class = {
      __inherits__ = function (out)
        return {
          out.Slipe.Client.Vehicles.BaseVehicleModel
        }
      end,
      getBf400 = getBf400,
      getFaggio = getFaggio,
      getFcr900 = getFcr900,
      getFreeway = getFreeway,
      getHpv1000 = getHpv1000,
      getNrg500 = getNrg500,
      getPcj600 = getPcj600,
      getPizzaboy = getPizzaboy,
      getSanchez = getSanchez,
      getWayfarer = getWayfarer,
      getQuadbike = getQuadbike,
      getBike = getBike,
      getBmx = getBmx,
      getMountainbike = getMountainbike,
      getAlpha = getAlpha,
      getBanshee = getBanshee,
      getBuffalo = getBuffalo,
      getBullet = getBullet,
      getCheetah = getCheetah,
      getComet = getComet,
      getElegy = getElegy,
      getEuros = getEuros,
      getFlash = getFlash,
      getInfernus = getInfernus,
      getJester = getJester,
      getPhoenix = getPhoenix,
      getSultan = getSultan,
      getSupergt = getSupergt,
      getTurismo = getTurismo,
      getUranus = getUranus,
      getWindsor = getWindsor,
      getZr350 = getZr350,
      getBlade = getBlade,
      getBroadway = getBroadway,
      getBuccaneer = getBuccaneer,
      getEsperanto = getEsperanto,
      getRemington = getRemington,
      getSavanna = getSavanna,
      getSlamvan = getSlamvan,
      getTornado = getTornado,
      getVoodoo = getVoodoo,
      getBlistacompact = getBlistacompact,
      getBravura = getBravura,
      getCadrona = getCadrona,
      getClover = getClover,
      getFeltzer = getFeltzer,
      getFortune = getFortune,
      getHermes = getHermes,
      getHustler = getHustler,
      getMajestic = getMajestic,
      getManana = getManana,
      getPrevion = getPrevion,
      getSabre = getSabre,
      getStallion = getStallion,
      getTampa = getTampa,
      getVirgo = getVirgo,
      getAdmiral = getAdmiral,
      getElegant = getElegant,
      getEmperor = getEmperor,
      getGlendale = getGlendale,
      getGreenwood = getGreenwood,
      getIntruder = getIntruder,
      getMerit = getMerit,
      getNebula = getNebula,
      getOceanic = getOceanic,
      getPremier = getPremier,
      getPrimo = getPrimo,
      getSentinel = getSentinel,
      getStafford = getStafford,
      getStretch = getStretch,
      getSunrise = getSunrise,
      getTahoma = getTahoma,
      getVincent = getVincent,
      getWashington = getWashington,
      getWillard = getWillard,
      getAmbulance = getAmbulance,
      getBarracks = getBarracks,
      getEnforcer = getEnforcer,
      getFbirancher = getFbirancher,
      getFbitruck = getFbitruck,
      getFiretruckladder = getFiretruckladder,
      getPolicecarls = getPolicecarls,
      getPolicecarlv = getPolicecarlv,
      getPolicecarsf = getPolicecarsf,
      getPoliceranger = getPoliceranger,
      getCementtruck = getCementtruck,
      getDft30 = getDft30,
      getDozer = getDozer,
      getDumper = getDumper,
      getDune = getDune,
      getFlatbed = getFlatbed,
      getForklift = getForklift,
      getLinerunner = getLinerunner,
      getPacker = getPacker,
      getRoadtrain = getRoadtrain,
      getSweeper = getSweeper,
      getTanker = getTanker,
      getTowtruck = getTowtruck,
      getTrashmaster = getTrashmaster,
      getUtilityvan = getUtilityvan,
      getBenson = getBenson,
      getBlackboxville = getBlackboxville,
      getBobcat = getBobcat,
      getBoxville = getBoxville,
      getMule = getMule,
      getPicador = getPicador,
      getSadler = getSadler,
      getSecuricar = getSecuricar,
      getWalton = getWalton,
      getYankee = getYankee,
      getYosemite = getYosemite,
      getBerkleysrcvan = getBerkleysrcvan,
      getBurrito = getBurrito,
      getCamper = getCamper,
      getJourney = getJourney,
      getMoonbeam = getMoonbeam,
      getNewsvan = getNewsvan,
      getPony = getPony,
      getRumpo = getRumpo,
      getBaggage = getBaggage,
      getBandito = getBandito,
      getBfinjection = getBfinjection,
      getBloodringbanger = getBloodringbanger,
      getBus = getBus,
      getCaddy = getCaddy,
      getCoach = getCoach,
      getCombineharvester = getCombineharvester,
      getHotdog = getHotdog,
      getHotknife = getHotknife,
      getHotringracer1 = getHotringracer1,
      getHotringracer2 = getHotringracer2,
      getHotringracer3 = getHotringracer3,
      getMonster1 = getMonster1,
      getMonster2 = getMonster2,
      getMonster3 = getMonster3,
      getMower = getMower,
      getMrwhoopee = getMrwhoopee,
      getKart = getKart,
      getTractor = getTractor,
      getTug = getTug,
      getVortex = getVortex,
      getRcBandit = getRcBandit,
      getRcFlowerpot = getRcFlowerpot,
      getRcTiger = getRcTiger,
      getClub = getClub,
      getHuntley = getHuntley,
      getLandstalker = getLandstalker,
      getMesa = getMesa,
      getPatriot = getPatriot,
      getPerennial = getPerennial,
      getRancher = getRancher,
      getRegina = getRegina,
      getRomero = getRomero,
      getSandking = getSandking,
      getSolair = getSolair,
      getStratum = getStratum,
      __ctor__ = __ctor__
    }
    return class
  end)
end)
