-- Generated by CSharp.lua Compiler
local System = System
local SlipeMtaDefinitions
System.import(function (out)
  SlipeMtaDefinitions = Slipe.MtaDefinitions
end)
System.namespace("Slipe.Client.IO", function (namespace)
  -- <summary>
  -- Class that handles various types of user input
  -- </summary>
  namespace.class("Input", function (namespace)
    local IsKeyPressed
    IsKeyPressed = function (keyName)
      return SlipeMtaDefinitions.MtaClient.GetKeyState(keyName)
    end
    return {
      IsKeyPressed = IsKeyPressed,
      __metadata__ = function (out)
        return {
          methods = {
            { "IsKeyPressed", 0x18E, IsKeyPressed, System.String, System.Boolean }
          },
          events = {
            { "OnKey", 0xE, System.Delegate(out.Slipe.Client.Elements.RootElement, out.Slipe.Client.IO.Events.OnKeyEventArgs, System.Void) },
            { "OnCharacter", 0xE, System.Delegate(out.Slipe.Client.Elements.RootElement, out.Slipe.Client.IO.Events.OnCharacterEventArgs, System.Void) }
          },
          class = { 0xE }
        }
      end
    }
  end)
end)
