-- Generated by CSharp.lua Compiler
local System = System
local SlipeClientElements
local SlipeClientIO
System.import(function (out)
  SlipeClientElements = Slipe.Client.Elements
  SlipeClientIO = Slipe.Client.IO
end)
System.namespace("Slipe.Client.IO", function (namespace)
  -- <summary>
  -- Class that handles various types of user input
  -- </summary>
  namespace.class("Input", function (namespace)
    local getInstance, getCursor, class, __ctor__
    __ctor__ = function (this)
      SlipeClientElements.RootElement.OnKey = SlipeClientElements.RootElement.OnKey + function (key, isPressed)
        local default = class.OnKey
        if default ~= nil then
          default(key, isPressed)
        end
      end
      SlipeClientElements.RootElement.OnCharacter = SlipeClientElements.RootElement.OnCharacter + function (character)
        local default = class.OnCharacter
        if default ~= nil then
          default(character)
        end
      end
    end
    getInstance = function ()
      class.instance = class.instance or class()
      return class.instance
    end
    getCursor = function (this)
      return SlipeClientIO.Cursor.getInstance()
    end
    class = {
      getInstance = getInstance,
      getCursor = getCursor,
      __ctor__ = __ctor__
    }
    return class
  end)
end)
