-- Generated by CSharp.lua Compiler
local System = System
local SlipeMtaDefinitions
System.import(function (out)
  SlipeMtaDefinitions = Slipe.MtaDefinitions
end)
System.namespace("Slipe.Client.IO", function (namespace)
  namespace.class("MtaConsole", function (namespace)
    local getActive, WriteLine
    getActive = function (this)
      return SlipeMtaDefinitions.MtaClient.IsConsoleActive()
    end
    WriteLine = function (this, line)
      SlipeMtaDefinitions.MtaClient.OutputConsole(line)
    end
    return {
      getActive = getActive,
      WriteLine = WriteLine
    }
  end)
end)
