-- Generated by CSharp.lua Compiler
local System = System
local SlipeMtaDefinitions
System.import(function (out)
  SlipeMtaDefinitions = Slipe.MtaDefinitions
end)
System.namespace("Slipe.Client.IO", function (namespace)
  namespace.class("MtaDebug", function (namespace)
    local getActive
    getActive = function ()
      return SlipeMtaDefinitions.MtaClient.IsDebugViewActive()
    end
    return {
      __inherits__ = function (out)
        return {
          out.Slipe.Shared.IO.SharedMtaDebug
        }
      end,
      getActive = getActive,
      __metadata__ = function (out)
        return {
          properties = {
            { "Active", 0x20E, System.Boolean, getActive }
          },
          events = {
            { "OnMessage", 0xE, System.Delegate(out.Slipe.Client.Elements.RootElement, out.Slipe.Client.IO.Events.OnDebugMessageEventArgs, System.Void) }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
