-- Generated by CSharp.lua Compiler
local System = System
local SlipeMtaDefinitions
local SlipeSharedIO
System.import(function (out)
  SlipeMtaDefinitions = Slipe.MtaDefinitions
  SlipeSharedIO = Slipe.Shared.IO
end)
System.namespace("Slipe.Client.IO", function (namespace)
  namespace.class("MtaDebug", function (namespace)
    local getActive, HandleMessage, class
    getActive = function (this)
      return SlipeMtaDefinitions.MtaClient.IsDebugViewActive()
    end
    HandleMessage = function (this, message, level, file, line, color)
      local default = class.OnMessage
      if default ~= nil then
        default(message, level, file, line, color)
      end
    end
    class = {
      __inherits__ = function (out)
        return {
          out.Slipe.Shared.IO.SharedMtaDebug
        }
      end,
      getActive = getActive,
      HandleMessage = HandleMessage
    }
    return class
  end)
end)
