-- Generated by CSharp.lua Compiler
local System = System
local SlipeMtaDefinitions
local SlipeSharedCollisionShapes
System.import(function (out)
  SlipeMtaDefinitions = Slipe.MtaDefinitions
  SlipeSharedCollisionShapes = Slipe.Shared.CollisionShapes
end)
System.namespace("Slipe.Shared.CollisionShapes", function (namespace)
  -- <summary>
  -- This is a shape that has a position and a 2D (X/Y) radius and a height.
  -- </summary>
  namespace.class("CollisionTube", function (namespace)
    local __ctor1__, __ctor2__
    __ctor1__ = function (this, element)
      SlipeSharedCollisionShapes.CollisionShape.__ctor__(this, element)
    end
    -- <summary>
    -- Creates a collision tube from a position, radius and height
    -- </summary>
    __ctor2__ = function (this, position, radius, height)
      __ctor1__(this, SlipeMtaDefinitions.MtaShared.CreateColTube(position.X, position.Y, position.Z, radius, height))
    end
    return {
      __inherits__ = function (out)
        return {
          out.Slipe.Shared.CollisionShapes.CollisionShape
        }
      end,
      __ctor__ = {
        __ctor1__,
        __ctor2__
      }
    }
  end)
end)
