-- Generated by CSharp.lua Compiler
local System = System
local SlipeMtaDefinitions
local SlipeServerElements
local SlipeServerPeds
local SlipeSharedElements
local DictStringDelegate
System.import(function (out)
  SlipeMtaDefinitions = Slipe.MtaDefinitions
  SlipeServerElements = Slipe.Server.Elements
  SlipeServerPeds = Slipe.Server.Peds
  SlipeSharedElements = Slipe.Shared.Elements
  DictStringDelegate = System.Dictionary(System.String, System.Delegate)
end)
System.namespace("Slipe.Server.Rpc", function (namespace)
  -- <summary>
  -- Manager class that handles RPC's between server and clients
  -- </summary>
  namespace.class("RpcManager", function (namespace)
    local instance, getInstance, RegisterRPC, TriggerRPC, TriggerRPC1, TriggerLatentRPC, TriggerLatentRPC1, class, 
    __ctor__
    __ctor__ = function (this)
      this.RegisteredRPCs = DictStringDelegate()

      SlipeServerElements.RootElement.OnMiscelaniousEvent = SlipeServerElements.RootElement.OnMiscelaniousEvent + function (eventName, source, p1, p2, p3, p4, p5, p6, p7, p8)
        if this.RegisteredRPCs:ContainsKey(eventName) then
          local player = SlipeSharedElements.ElementManager.getInstance():GetElement(source, SlipeServerPeds.Player)
          this.RegisteredRPCs:get(eventName)(player, p1)
        end
      end
    end
    getInstance = function ()
      if instance == nil then
        instance = class()
      end
      return instance
    end
    -- <summary>
    -- Register an RPC
    -- </summary>
    RegisterRPC = function (this, key, callback, CallbackType)
      this.RegisteredRPCs:set(key, function (player, parameters)
        callback(player, CallbackType(parameters))
      end)
      SlipeMtaDefinitions.MtaShared.AddEvent(key, true)
      SlipeSharedElements.Element.getRoot():ListenForEvent(key, true, "normal")
    end
    -- <summary>
    -- Trigger an RPC on a player
    -- </summary>
    TriggerRPC = function (this, target, key, argument)
      SlipeMtaDefinitions.MtaServer.TriggerClientEvent(target:getMTAElement(), key, SlipeSharedElements.Element.getRoot():getMTAElement(), argument)
    end
    -- <summary>
    -- Trigger an RPC
    -- </summary>
    TriggerRPC1 = function (this, key, argument)
      SlipeMtaDefinitions.MtaServer.TriggerClientEvent(SlipeSharedElements.Element.getRoot():getMTAElement(), key, SlipeSharedElements.Element.getRoot():getMTAElement(), argument)
    end
    -- <summary>
    -- Trigger an RPC with limited bandwidth
    -- </summary>
    TriggerLatentRPC = function (this, target, key, bandwidth, argument, persists)
      SlipeMtaDefinitions.MtaServer.TriggerLatentClientEvent(target:getMTAElement(), key, bandwidth, persists, SlipeSharedElements.Element.getRoot():getMTAElement(), argument)
    end
    -- <summary>
    -- Trigger an RPC with limited bandwidth
    -- </summary>
    TriggerLatentRPC1 = function (this, key, bandwidth, argument, persists)
      SlipeMtaDefinitions.MtaServer.TriggerLatentClientEvent(SlipeSharedElements.Element.getRoot():getMTAElement(), key, bandwidth, persists, SlipeSharedElements.Element.getRoot():getMTAElement(), argument)
    end
    class = {
      getInstance = getInstance,
      RegisterRPC = RegisterRPC,
      TriggerRPC = TriggerRPC,
      TriggerRPC1 = TriggerRPC1,
      TriggerLatentRPC = TriggerLatentRPC,
      TriggerLatentRPC1 = TriggerLatentRPC1,
      __ctor__ = __ctor__,
      __metadata__ = function (out)
        return {
          fields = {
            { "instance", 0x9, class },
            { "RegisteredRPCs", 0x1, System.Dictionary(System.String, System.Delegate(out.Slipe.Server.Peds.Player, System.Object, System.Void)) }
          },
          properties = {
            { "Instance", 0x20E, class, getInstance }
          },
          methods = {
            { ".ctor", 0x1, nil },
            { "RegisterRPC", 0x10206, RegisterRPC, function (CallbackType) return System.String, System.Delegate(out.Slipe.Server.Peds.Player, CallbackType, System.Void) end },
            { "TriggerLatentRPC", 0x506, TriggerLatentRPC, out.Slipe.Server.Peds.Player, System.String, System.Int32, System.Object, System.Boolean },
            { "TriggerLatentRPC", 0x406, TriggerLatentRPC1, System.String, System.Int32, System.Object, System.Boolean },
            { "TriggerRPC", 0x306, TriggerRPC, out.Slipe.Server.Peds.Player, System.String, System.Object },
            { "TriggerRPC", 0x206, TriggerRPC1, System.String, System.Object }
          },
          class = { 0x6 }
        }
      end
    }
    return class
  end)
end)
