-- Generated by CSharp.lua Compiler
local System = System
local SlipeSharedHelpers
local SystemNumerics
System.import(function (out)
  SlipeSharedHelpers = Slipe.Shared.Helpers
  SystemNumerics = System.Numerics
end)
System.namespace("Slipe.Client.Helpers", function (namespace)
  -- <summary>
  -- Abstract class that implements attaching functionality in a lazy way (updates only when update is called)
  -- </summary>
  namespace.class("LazyAttachableObject", function (namespace)
    local getToAttached, getIsAttached, AttachTo, AttachTo1, AttachTo2, AttachTo3, Detach, OnAttach, 
    OnDetach, __ctor__
    __ctor__ = function (this)
      this.Offset = System.default(SystemNumerics.Matrix4x4)
    end
    getToAttached = function (this)
      return this.toAttached
    end
    getIsAttached = function (this)
      return this.toAttached ~= nil
    end
    -- <summary>
    -- Attach this attachable to a toAttachable using a matrix to describe the positional and rotational offset
    -- </summary>
    AttachTo = function (this, toElement, offsetMatrix)
      this.toAttached = toElement
      this.Offset = offsetMatrix:__clone__()
      this:OnAttach()
    end
    -- <summary>
    -- Attach this attachable to a toAttachable with 2 vectors describing a position offset and a rotation offset
    -- </summary>
    AttachTo1 = function (this, toElement, positionOffset, rotationOffset)
      AttachTo2(this, toElement, positionOffset:__clone__(), SlipeSharedHelpers.NumericHelper.EulerToQuaternion(rotationOffset:__clone__()))
    end
    -- <summary>
    -- Attach this attachable to a toAttachable with a vector describing the position offset and a quaternion describing the rotation offset
    -- </summary>
    AttachTo2 = function (this, toElement, positionOffset, rotationOffset)
      AttachTo(this, toElement, SystemNumerics.Matrix4x4.Transform(SystemNumerics.Matrix4x4.CreateTranslation(positionOffset), rotationOffset))
    end
    -- <summary>
    -- Attach this attachable to a toAttachable without any offset
    -- </summary>
    AttachTo3 = function (this, toElement)
      AttachTo(this, toElement, SystemNumerics.Matrix4x4.getIdentity())
    end
    -- <summary>
    -- Detach this attachable
    -- </summary>
    Detach = function (this)
      this:OnDetach()
    end
    OnAttach = function (this)
    end
    OnDetach = function (this)
      this.toAttached = nil
    end
    return {
      getToAttached = getToAttached,
      getIsAttached = getIsAttached,
      AttachTo = AttachTo,
      AttachTo1 = AttachTo1,
      AttachTo2 = AttachTo2,
      AttachTo3 = AttachTo3,
      Detach = Detach,
      OnAttach = OnAttach,
      OnDetach = OnDetach,
      __ctor__ = __ctor__
    }
  end)
end)
