-- Generated by CSharp.lua Compiler
local System = System
local SlipeMtaDefinitions
System.import(function (out)
  SlipeMtaDefinitions = Slipe.MtaDefinitions
end)
System.namespace("Slipe.Client.GameWorld", function (namespace)
  -- <summary>
  -- Represents a SWAT rope that can be created
  -- </summary>
  namespace.class("SwatRope", function (namespace)
    local __ctor__
    __ctor__ = function (this, position, duration)
      SlipeMtaDefinitions.MtaClient.CreateSWATRope(position.X, position.Y, position.Z, duration)
    end
    return {
      __ctor__ = __ctor__
    }
  end)
end)
