-- Generated by CSharp.lua Compiler
local System = System
local SlipeMtaDefinitions
local SlipeSharedGameWorld
System.import(function (out)
  SlipeMtaDefinitions = Slipe.MtaDefinitions
  SlipeSharedGameWorld = Slipe.Shared.GameWorld
end)
System.namespace("Slipe.Client.GameWorld", function (namespace)
  -- <summary>
  -- Class used to create bodies of water on the map
  -- </summary>
  namespace.class("Water", function (namespace)
    local getLevel1, setLevel1, __ctor1__, __ctor2__, __ctor3__
    __ctor1__ = function (this, element)
      SlipeSharedGameWorld.SharedWater.__ctor__[1](this, element)
    end
    -- <summary>
    -- Creates a body of water from 4 corners. The order of the input vectors doesn't matter
    -- </summary>
    __ctor2__ = function (this, corner1, corner2, corner3, corner4, shallow)
      SlipeSharedGameWorld.SharedWater.__ctor__[2](this, corner1:__clone__(), corner2:__clone__(), corner3:__clone__(), corner4:__clone__(), shallow)
    end
    -- <summary>
    -- Creates a body of water from 3 corners. The order of the input vectors doesn't matter
    -- </summary>
    __ctor3__ = function (this, corner1, corner2, corner3, shallow)
      SlipeSharedGameWorld.SharedWater.__ctor__[3](this, corner1:__clone__(), corner2:__clone__(), corner3:__clone__(), shallow)
    end
    getLevel1 = function (this)
      return SlipeMtaDefinitions.MtaClient.GetWaterLevel(this.element)
    end
    setLevel1 = function (this, value)
      SlipeMtaDefinitions.MtaShared.SetWaterLevel(this.element, value)
    end
    return {
      __inherits__ = function (out)
        return {
          out.Slipe.Shared.GameWorld.SharedWater
        }
      end,
      getLevel1 = getLevel1,
      setLevel1 = setLevel1,
      __ctor__ = {
        __ctor1__,
        __ctor2__,
        __ctor3__
      },
      __metadata__ = function (out)
        return {
          class = { 0x6, System.new(out.Slipe.Shared.Elements.DefaultElementClassAttribute, 2, 34 --[[ElementType.Water]]) }
        }
      end
    }
  end)
end)
