-- Generated by CSharp.lua Compiler
local System = System
local SlipeMtaDefinitions
local SlipeSharedWeapons
System.import(function (out)
  SlipeMtaDefinitions = Slipe.MtaDefinitions
  SlipeSharedWeapons = Slipe.Shared.Weapons
end)
System.namespace("Slipe.Server.Weapons", function (namespace)
  namespace.class("WeaponModel", function (namespace)
    local getJetPackEnabled, setJetPackEnabled, __ctor1__, __ctor2__
    -- <summary>
    -- Get a weapon model from the weapon name
    -- </summary>
    __ctor1__ = function (this, name)
      SlipeSharedWeapons.SharedWeaponModel.__ctor__[2](this, name)
    end
    -- <summary>
    -- Get a weapon model from the weapon id
    -- </summary>
    __ctor2__ = function (this, id)
      SlipeSharedWeapons.SharedWeaponModel.__ctor__[1](this, id)
    end
    getJetPackEnabled = function (this)
      return SlipeMtaDefinitions.MtaServer.GetJetpackWeaponEnabled(this:getName())
    end
    setJetPackEnabled = function (this, value)
      SlipeMtaDefinitions.MtaServer.SetJetpackWeaponEnabled(this:getName(), value)
    end
    return {
      __inherits__ = function (out)
        return {
          out.Slipe.Shared.Weapons.SharedWeaponModel
        }
      end,
      getJetPackEnabled = getJetPackEnabled,
      setJetPackEnabled = setJetPackEnabled,
      __ctor__ = {
        __ctor1__,
        __ctor2__
      }
    }
  end)
end)
