-- Generated by CSharp.lua Compiler
local System = System
local SlipeSharedGameWorld
System.import(function (out)
  SlipeSharedGameWorld = Slipe.Shared.GameWorld
end)
System.namespace("Slipe.Server.GameWorld", function (namespace)
  -- <summary>
  -- Class wrapping a garage as seen in singleplayer
  -- </summary>
  namespace.class("Garage", function (namespace)
    local __ctor__
    __ctor__ = function (this, garage)
      SlipeSharedGameWorld.SharedGarage.__ctor__(this, garage)
    end
    return {
      __inherits__ = function (out)
        return {
          out.Slipe.Shared.GameWorld.SharedGarage
        }
      end,
      __ctor__ = __ctor__
    }
  end)
end)
