-- Generated by CSharp.lua Compiler
local System = System
local SlipeServerGameWorld
local SlipeSharedGameWorld
System.import(function (out)
  SlipeServerGameWorld = Slipe.Server.GameWorld
  SlipeSharedGameWorld = Slipe.Shared.GameWorld
end)
System.namespace("Slipe.Server.GameWorld", function (namespace)
  namespace.class("World", function (namespace)
    local getInstance1, GetGarage1, class
    getInstance1 = function ()
      if SlipeSharedGameWorld.SharedWorld.instance == nil then
        SlipeSharedGameWorld.SharedWorld.instance = class()
      end
      return System.cast(class, SlipeSharedGameWorld.SharedWorld.instance)
    end
    -- <summary>
    -- Get a specific garage class instance from a garage ID
    -- </summary>
    GetGarage1 = function (this, garage)
      return SlipeServerGameWorld.Garage(garage)
    end
    class = {
      __inherits__ = function (out)
        return {
          out.Slipe.Shared.GameWorld.SharedWorld
        }
      end,
      getInstance1 = getInstance1,
      GetGarage1 = GetGarage1
    }
    return class
  end)
end)
