-- Generated by CSharp.lua Compiler
local System = System
local SlipeMtaDefinitions
local SlipeSharedElements
System.import(function (out)
  SlipeMtaDefinitions = Slipe.MtaDefinitions
  SlipeSharedElements = Slipe.Shared.Elements
end)
System.namespace("Slipe.Server.IO", function (namespace)
  namespace.class("MtaConsole", function (namespace)
    local WriteLine, WriteLine1
    WriteLine = function (this, line, player)
      SlipeMtaDefinitions.MtaServer.OutputConsole(line, player:getMTAElement())
    end
    WriteLine1 = function (this, line)
      SlipeMtaDefinitions.MtaServer.OutputConsole(line, SlipeSharedElements.Element.getRoot():getMTAElement())
    end
    return {
      WriteLine = WriteLine,
      WriteLine1 = WriteLine1
    }
  end)
end)
