-- Generated by CSharp.lua Compiler
local System = System
local SlipeSharedIO
System.import(function (out)
  SlipeSharedIO = Slipe.Shared.IO
end)
System.namespace("Slipe.Server.IO", function (namespace)
  namespace.class("MtaDebug", function (namespace)
    local HandleMessage, class
    HandleMessage = function (this, message, level, file, line, color)
      local default = class.OnMessage
      if default ~= nil then
        default(message, level, file, line, color)
      end
    end
    class = {
      __inherits__ = function (out)
        return {
          out.Slipe.Shared.IO.SharedMtaDebug
        }
      end,
      HandleMessage = HandleMessage
    }
    return class
  end)
end)
