-- Generated by CSharp.lua Compiler
local System = System
local SlipeMtaDefinitions
System.import(function (out)
  SlipeMtaDefinitions = Slipe.MtaDefinitions
end)
System.namespace("Slipe.Server.IO", function (namespace)
  namespace.class("ServerLog", function (namespace)
    local WriteLine
    WriteLine = function (this, line)
      SlipeMtaDefinitions.MtaServer.OutputServerLog(line)
    end
    return {
      WriteLine = WriteLine
    }
  end)
end)
