-- Generated by CSharp.lua Compiler
local System = System
local SlipeMtaDefinitions
System.import(function (out)
  SlipeMtaDefinitions = Slipe.MtaDefinitions
end)
System.namespace("Slipe.Shared.Cryptography", function (namespace)
  -- <summary>
  -- Represents static wrappers for hasing strings with Bcrypt
  -- </summary>
  namespace.class("Bcrypt", function (namespace)
    local Hash, Verify
    -- <summary>
    -- Hash a string with the Bcrypt algorithm
    -- </summary>
    Hash = function (input, cost)
      return SlipeMtaDefinitions.MtaPasswords.Hash(input, cost)
    end
    -- <summary>
    -- Verify an input string against a Bcrypt hash
    -- </summary>
    Verify = function (input, hash)
      return SlipeMtaDefinitions.MtaPasswords.Verify(input, hash)
    end
    return {
      Hash = Hash,
      Verify = Verify
    }
  end)
end)
