-- Generated by CSharp.lua Compiler
local System = System
local SlipeSharedElements
local SlipeSharedHelpers
local SystemNumerics
System.import(function (out)
  SlipeSharedElements = Slipe.Shared.Elements
  SlipeSharedHelpers = Slipe.Shared.Helpers
  SystemNumerics = System.Numerics
end)
System.namespace("Slipe.Client.SightLines", function (namespace)
  -- <summary>
  -- Class that wraps the huge amount of data that can be retrieved from SightLine Process
  -- </summary>
  namespace.class("SightLineData", function (namespace)
    local getBodyPart, getVehiclePart, __ctor__
    -- <summary>
    -- Create a data instance from the raw ProcessLineOfSight output
    -- </summary>
    __ctor__ = function (this, d)
      this.CollisionPosition = System.default(SystemNumerics.Vector3)
      this.Normal = System.default(SystemNumerics.Vector3)
      this.WorldModelMatrix = System.default(SystemNumerics.Matrix4x4)
      this.DidHit = d[1]
      if this.DidHit then
        this.CollisionPosition = SystemNumerics.Vector3(d[2], d[3], d[4])
        if d[5] ~= nil then
          this.HitElement = SlipeSharedElements.ElementManager.getInstance():GetElement(d[5], SlipeSharedElements.PhysicalElement)
        end
        this.Normal = SystemNumerics.Vector3(d[6], d[7], d:getRest()[1])
        this.SurfaceMaterial = d:getRest()[2]
        this.Lighting = d:getRest()[3]
        this.piece = d:getRest()[4]
        this.WorldModelID = d:getRest()[5]

        this.WorldModelMatrix = SystemNumerics.Matrix4x4.op_Addition(SystemNumerics.Matrix4x4.CreateTranslation(d:getRest()[6], d:getRest()[7], d:getRest():getRest()[1]), SystemNumerics.Matrix4x4.CreateFromQuaternion(SlipeSharedHelpers.NumericHelper.EulerToQuaternion(SystemNumerics.Vector3(d:getRest():getRest()[2], d:getRest():getRest()[3], d:getRest():getRest()[4]))))
        this.WorldLODModelID = d:getRest()[5]
      end
    end
    getBodyPart = function (this)
      return this.piece
    end
    getVehiclePart = function (this)
      return this.piece
    end
    return {
      piece = 0,
      DidHit = false,
      SurfaceMaterial = 0,
      Lighting = 0,
      getBodyPart = getBodyPart,
      getVehiclePart = getVehiclePart,
      WorldModelID = 0,
      WorldLODModelID = 0,
      __ctor__ = __ctor__
    }
  end)
end)
