-- Generated by CSharp.lua Compiler
local System = System
System.namespace("Slipe.Server.Accounts", function (namespace)
  namespace.class("AccountException", function (namespace)
    local __ctor__
    __ctor__ = function (this, message)
      System.Exception.__ctor__(this, message)
    end
    return {
      __inherits__ = function (out)
        return {
          System.Exception
        }
      end,
      __ctor__ = __ctor__
    }
  end)
end)
