-- Generated by CSharp.lua Compiler
local System = System
local SlipeClientBrowsers
local SlipeClientGame
local SlipeClientIO
local SlipeSharedElements
local SlipeSharedIO
local SlipeSharedPeds
System.import(function (out)
  SlipeClientBrowsers = Slipe.Client.Browsers
  SlipeClientGame = Slipe.Client.Game
  SlipeClientIO = Slipe.Client.IO
  SlipeSharedElements = Slipe.Shared.Elements
  SlipeSharedIO = Slipe.Shared.IO
  SlipeSharedPeds = Slipe.Shared.Peds
end)
System.namespace("Slipe.Client.Elements", function (namespace)
  namespace.class("RootElement", function (namespace)
    local HandleEvent, initEnums, class, __ctor__
    __ctor__ = function (this, element)
      SlipeSharedElements.Element.__ctor__[2](this, element)
      class.OnPreRender = class.OnPreRender + function (timeSlice)
        SlipeClientGame.GameClient.HandleUpdate(timeSlice)
      end
      class.OnChatMessage = class.OnChatMessage + function (message, color)
        SlipeClientIO.ChatBox.HandleMessage(message, color)
      end
      class.OnDebugMessage = class.OnDebugMessage + function (message, level, file, line, color)
        SlipeClientGame.GameClient.getDebug():HandleMessage(message, level, file, line, color)
      end
      class.OnBrowserWhiteListChange = class.OnBrowserWhiteListChange + function (changed)
        SlipeClientBrowsers.Browser.HandleWhiteListChange(changed)
      end
      class.OnMinimize = class.OnMinimize + function ()
        SlipeClientGame.GameClient.HandleMinimize()
      end
      this.OnNetworkInteruption = this.OnNetworkInteruption + function (status, ticksSinceInteruptionStarted)
        SlipeClientGame.GameClient.HandleNetworkInteruption(status, ticksSinceInteruptionStarted)
      end
      this.OnRestore = this.OnRestore + function (didClearRenderTargets)
        SlipeClientGame.GameClient.HandleRestore(didClearRenderTargets)
      end
    end
    HandleEvent = function (this, eventName, element, p1, p2, p3, p4, p5, p6, p7, p8)
      local default = class.OnMiscelaniousEvent
      if default ~= nil then
        default(eventName, element, p1, p2, p3, p4, p5, p6, p7, p8)
      end
    end
    initEnums = function (this)
      local m = System.cast(System.Int32, System.Enum.Parse(System.typeof(SlipeSharedIO.MouseButton), "Left", true))
      local s = System.cast(System.Int32, System.Enum.Parse(System.typeof(SlipeSharedIO.MouseButtonState), "Down", true))
      local q = System.cast(System.Int32, System.Enum.Parse(System.typeof(SlipeSharedPeds.QuitType), "Disconnected", true))
    end
    class = {
      __inherits__ = function (out)
        return {
          out.Slipe.Shared.Elements.Element
        }
      end,
      HandleEvent = HandleEvent,
      __ctor__ = __ctor__,
      __metadata__ = function (out)
        return {
          class = { 0x6, System.new(out.Slipe.Shared.Elements.DefaultElementClassAttribute, 2, 36 --[[ElementType.Root]]) }
        }
      end
    }
    return class
  end)
end)
