-- Generated by CSharp.lua Compiler
local System = System
local SlipeClientGui
System.import(function (out)
  SlipeClientGui = Slipe.Client.Gui
end)
System.namespace("Slipe.Client.Gui", function (namespace)
  -- <summary>
  -- Represents an editable Gui element
  -- </summary>
  namespace.class("EditableGuiElement", function (namespace)
    local __ctor__
    __ctor__ = function (this, element)
      SlipeClientGui.GuiElement.__ctor__(this, element)
    end
    return {
      __inherits__ = function (out)
        return {
          out.Slipe.Client.Gui.GuiElement
        }
      end,
      __ctor__ = __ctor__
    }
  end)
end)
