-- Generated by CSharp.lua Compiler
local System = System
local SlipeMtaDefinitions
System.import(function (out)
  SlipeMtaDefinitions = Slipe.MtaDefinitions
end)
System.namespace("Slipe.Client.Gui", function (namespace)
  -- <summary>
  -- Represents a column in a grid list
  -- </summary>
  namespace.class("GridColumn", function (namespace)
    local getTitle, setTitle, getAbsoluteWidth, setAbsoluteWidth, getRelativeWidth, setRelativeWidth, AutoSize, __ctor__
    -- <summary>
    -- Create a new column
    -- </summary>
    __ctor__ = function (this, title, width, gridList)
      this.ID = SlipeMtaDefinitions.MtaClient.GuiGridListAddColumn(gridList:getMTAElement(), title, width)
      this.glist = gridList
    end
    getTitle = function (this)
      return SlipeMtaDefinitions.MtaClient.GuiGridListGetColumnTitle(this.glist:getMTAElement(), this.ID)
    end
    setTitle = function (this, value)
      SlipeMtaDefinitions.MtaClient.GuiGridListSetColumnTitle(this.glist:getMTAElement(), this.ID, value)
    end
    getAbsoluteWidth = function (this)
      return SlipeMtaDefinitions.MtaClient.GuiGridListGetColumnWidth(this.glist:getMTAElement(), this.ID, false)
    end
    setAbsoluteWidth = function (this, value)
      SlipeMtaDefinitions.MtaClient.GuiGridListSetColumnWidth(this.glist:getMTAElement(), this.ID, value, false)
    end
    getRelativeWidth = function (this)
      return SlipeMtaDefinitions.MtaClient.GuiGridListGetColumnWidth(this.glist:getMTAElement(), this.ID, true)
    end
    setRelativeWidth = function (this, value)
      SlipeMtaDefinitions.MtaClient.GuiGridListSetColumnWidth(this.glist:getMTAElement(), this.ID, value, true)
    end
    -- <summary>
    -- This allows you to automatically size a column to display everything in it correctly, with the most minimal width.
    -- </summary>
    AutoSize = function (this)
      return SlipeMtaDefinitions.MtaClient.GuiGridListAutoSizeColumn(this.glist:getMTAElement(), this.ID)
    end
    return {
      ID = 0,
      getTitle = getTitle,
      setTitle = setTitle,
      getAbsoluteWidth = getAbsoluteWidth,
      setAbsoluteWidth = setAbsoluteWidth,
      getRelativeWidth = getRelativeWidth,
      setRelativeWidth = setRelativeWidth,
      AutoSize = AutoSize,
      __ctor__ = __ctor__
    }
  end)
end)
