-- Generated by CSharp.lua Compiler
local System = System
local SlipeMtaDefinitions
System.import(function (out)
  SlipeMtaDefinitions = Slipe.MtaDefinitions
end)
System.namespace("Slipe.Client.Gui", function (namespace)
  -- <summary>
  -- Represents a row in a grid list
  -- </summary>
  namespace.class("GridRow", function (namespace)
    local __ctor1__, __ctor2__
    -- <summary>
    -- Create a new row
    -- </summary>
    __ctor1__ = function (this, gridList)
      this.ID = SlipeMtaDefinitions.MtaClient.GuiGridListAddRow(gridList:getMTAElement())
      this.glist = gridList
    end
    -- <summary>
    -- Create a new row after an existing row index
    -- </summary>
    __ctor2__ = function (this, gridList, index)
      this.ID = SlipeMtaDefinitions.MtaClient.GuiGridListInsertRowAfter(gridList:getMTAElement(), index)
      this.glist = gridList
    end
    return {
      ID = 0,
      __ctor__ = {
        __ctor1__,
        __ctor2__
      }
    }
  end)
end)
