-- Generated by CSharp.lua Compiler
local System = System
local SlipeClientGui
local SlipeMtaDefinitions
local SlipeSharedElements
local SystemNumerics
System.import(function (out)
  SlipeClientGui = Slipe.Client.Gui
  SlipeMtaDefinitions = Slipe.MtaDefinitions
  SlipeSharedElements = Slipe.Shared.Elements
  SystemNumerics = System.Numerics
end)
System.namespace("Slipe.Client.Gui", function (namespace)
  namespace.class("GuiElement", function (namespace)
    local getVisible, setVisible, getAlpha, setAlpha, getEnabled, setEnabled, getStandardFont, setStandardFont, 
    getCustomFont, setCustomFont, getPosition, setPosition, getRelativePosition, setRelativePosition, getSize, setSize, 
    getRelativeSize, setRelativeSize, getContent, setContent, BringToFront, MoveToBack, Blur, Focus, 
    SetProperty, GetProperty, __ctor__
    __ctor__ = function (this, element)
      SlipeSharedElements.Element.__ctor__[2](this, element)
    end
    getVisible = function (this)
      return SlipeMtaDefinitions.MtaClient.GuiGetVisible(this.element)
    end
    setVisible = function (this, value)
      SlipeMtaDefinitions.MtaClient.GuiSetVisible(this.element, value)
    end
    getAlpha = function (this)
      return SlipeMtaDefinitions.MtaClient.GuiGetAlpha(this.element)
    end
    setAlpha = function (this, value)
      SlipeMtaDefinitions.MtaClient.GuiSetAlpha(this.element, value)
    end
    getEnabled = function (this)
      return SlipeMtaDefinitions.MtaClient.GuiGetEnabled(this.element)
    end
    setEnabled = function (this, value)
      SlipeMtaDefinitions.MtaClient.GuiSetEnabled(this.element, value)
    end
    getStandardFont = function (this)
      s, _ = SlipeMtaDefinitions.MtaClient.GuiGetFont(this.element):Deconstruct()
      return System.cast(System.Int32, System.Enum.Parse(System.typeof(SlipeClientGui.StandardGuiFont), s:Replace("-", "_"), true))
    end
    setStandardFont = function (this, value)
      SlipeMtaDefinitions.MtaClient.GuiSetFont(this.element, value:ToEnumString(SlipeClientGui.StandardGuiFont):ToLower():Replace("_", "-"))
    end
    getCustomFont = function (this)
      _, e = SlipeMtaDefinitions.MtaClient.GuiGetFont(this.element):Deconstruct()
      return SlipeSharedElements.ElementManager.getInstance():GetElement(e, SlipeClientGui.GuiFont)
    end
    setCustomFont = function (this, value)
      SlipeMtaDefinitions.MtaClient.GuiSetFont(this.element, value:getMTAElement())
    end
    getPosition = function (this)
      x, y = SlipeMtaDefinitions.MtaClient.GuiGetPosition(this.element, false):Deconstruct()
      return SystemNumerics.Vector2(x, y)
    end
    setPosition = function (this, value)
      SlipeMtaDefinitions.MtaClient.GuiSetPosition(this.element, value.X, value.Y, false)
    end
    getRelativePosition = function (this)
      x, y = SlipeMtaDefinitions.MtaClient.GuiGetPosition(this.element, true):Deconstruct()
      return SystemNumerics.Vector2(x, y)
    end
    setRelativePosition = function (this, value)
      SlipeMtaDefinitions.MtaClient.GuiSetPosition(this.element, value.X, value.Y, true)
    end
    getSize = function (this)
      x, y = SlipeMtaDefinitions.MtaClient.GuiGetSize(this.element, false):Deconstruct()
      return SystemNumerics.Vector2(x, y)
    end
    setSize = function (this, value)
      SlipeMtaDefinitions.MtaClient.GuiSetSize(this.element, value.X, value.Y, false)
    end
    getRelativeSize = function (this)
      x, y = SlipeMtaDefinitions.MtaClient.GuiGetSize(this.element, true):Deconstruct()
      return SystemNumerics.Vector2(x, y)
    end
    setRelativeSize = function (this, value)
      SlipeMtaDefinitions.MtaClient.GuiSetSize(this.element, value.X, value.Y, true)
    end
    getContent = function (this)
      return SlipeMtaDefinitions.MtaClient.GuiGetText(this.element)
    end
    setContent = function (this, value)
      SlipeMtaDefinitions.MtaClient.GuiSetText(this.element, value)
    end
    -- <summary>
    -- This function brings a Gui element on top of others.
    -- </summary>
    BringToFront = function (this)
      return SlipeMtaDefinitions.MtaClient.GuiBringToFront(this.element)
    end
    -- <summary>
    -- This function moves a GUI element to the very back of all other GUI elements.
    -- </summary>
    MoveToBack = function (this)
      return SlipeMtaDefinitions.MtaClient.GuiMoveToBack(this.element)
    end
    -- <summary>
    -- Blur this Gui Element
    -- </summary>
    Blur = function (this)
      return SlipeMtaDefinitions.MtaClient.GuiBlur(this.element)
    end
    -- <summary>
    -- Focus on this Gui Element
    -- </summary>
    Focus = function (this)
      return SlipeMtaDefinitions.MtaClient.GuiFocus(this.element)
    end
    -- <summary>
    -- Set a Cegui property
    -- </summary>
    SetProperty = function (this, property, value)
      return SlipeMtaDefinitions.MtaClient.GuiSetProperty(this.element, property, value)
    end
    -- <summary>
    -- Get a Cegui property
    -- </summary>
    GetProperty = function (this, property)
      return SlipeMtaDefinitions.MtaClient.GuiGetProperty(this.element, property)
    end
    return {
      __inherits__ = function (out)
        return {
          out.Slipe.Shared.Elements.Element
        }
      end,
      getVisible = getVisible,
      setVisible = setVisible,
      getAlpha = getAlpha,
      setAlpha = setAlpha,
      getEnabled = getEnabled,
      setEnabled = setEnabled,
      getStandardFont = getStandardFont,
      setStandardFont = setStandardFont,
      getCustomFont = getCustomFont,
      setCustomFont = setCustomFont,
      getPosition = getPosition,
      setPosition = setPosition,
      getRelativePosition = getRelativePosition,
      setRelativePosition = setRelativePosition,
      getSize = getSize,
      setSize = setSize,
      getRelativeSize = getRelativeSize,
      setRelativeSize = setRelativeSize,
      getContent = getContent,
      setContent = setContent,
      BringToFront = BringToFront,
      MoveToBack = MoveToBack,
      Blur = Blur,
      Focus = Focus,
      SetProperty = SetProperty,
      GetProperty = GetProperty,
      __ctor__ = __ctor__
    }
  end)
end)
