-- Generated by CSharp.lua Compiler
local System = System
local SlipeClientGui
local SlipeMtaDefinitions
System.import(function (out)
  SlipeClientGui = Slipe.Client.Gui
  SlipeMtaDefinitions = Slipe.MtaDefinitions
end)
System.namespace("Slipe.Client.Gui", function (namespace)
  -- <summary>
  -- Represents a Cegui radio button
  -- </summary>
  namespace.class("RadioButton", function (namespace)
    local getSelected, setSelected, __ctor1__, __ctor2__
    __ctor1__ = function (this, element)
      SlipeClientGui.GuiElement.__ctor__(this, element)
    end
    -- <summary>
    -- Create a radio button
    -- </summary>
    __ctor2__ = function (this, position, dimensions, content, relative, parent)
      local default = parent
      if default ~= nil then
        default = default:getMTAElement()
      end
      __ctor1__(this, SlipeMtaDefinitions.MtaClient.GuiCreateRadioButton(position.X, position.Y, dimensions.X, dimensions.Y, content, relative, default))
    end
    getSelected = function (this)
      return SlipeMtaDefinitions.MtaClient.GuiRadioButtonGetSelected(this.element)
    end
    setSelected = function (this, value)
      SlipeMtaDefinitions.MtaClient.GuiRadioButtonSetSelected(this.element, value)
    end
    return {
      __inherits__ = function (out)
        return {
          out.Slipe.Client.Gui.GuiElement
        }
      end,
      getSelected = getSelected,
      setSelected = setSelected,
      __ctor__ = {
        __ctor1__,
        __ctor2__
      },
      __metadata__ = function (out)
        return {
          class = { 0x6, System.new(out.Slipe.Shared.Elements.DefaultElementClassAttribute, 2, 20 --[[ElementType.GuiRadioButton]]) }
        }
      end
    }
  end)
end)
