-- Generated by CSharp.lua Compiler
local System = System
local SlipeClientGui
local SlipeMtaDefinitions
local SlipeSharedElements
System.import(function (out)
  SlipeClientGui = Slipe.Client.Gui
  SlipeMtaDefinitions = Slipe.MtaDefinitions
  SlipeSharedElements = Slipe.Shared.Elements
end)
System.namespace("Slipe.Client.Gui", function (namespace)
  -- <summary>
  -- Represents a Cegui tab (use with tab panel)
  -- </summary>
  namespace.class("Tab", function (namespace)
    local Delete, __ctor1__, __ctor2__
    __ctor1__ = function (this, element)
      SlipeClientGui.GuiElement.__ctor__(this, element)
      this.parentPanel = SlipeSharedElements.ElementManager.getInstance():GetElement(SlipeMtaDefinitions.MtaShared.GetElementParent(element), SlipeClientGui.TabPanel)
    end
    -- <summary>
    -- Create a tab
    -- </summary>
    __ctor2__ = function (this, title, panel)
      __ctor1__(this, SlipeMtaDefinitions.MtaClient.GuiCreateTab(title, panel:getMTAElement()))
    end
    -- <summary>
    -- Delete this tab
    -- </summary>
    Delete = function (this)
      return SlipeMtaDefinitions.MtaClient.GuiDeleteTab(this.element, this.parentPanel:getMTAElement())
    end
    return {
      __inherits__ = function (out)
        return {
          out.Slipe.Client.Gui.GuiElement
        }
      end,
      Delete = Delete,
      __ctor__ = {
        __ctor1__,
        __ctor2__
      },
      __metadata__ = function (out)
        return {
          class = { 0x6, System.new(out.Slipe.Shared.Elements.DefaultElementClassAttribute, 2, 25 --[[ElementType.GuiTab]]) }
        }
      end
    }
  end)
end)
